### PR TITLE
Fix Prometheus server crash on listening to already used port

### LINKED ISSUE #1903: Prometheus example crashes
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.
- windows 10 x64
- ubuntu gcc x64

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
- run prometheus in docker container
- compile opentelemetry via cmake with the WITH_PROMETHEUS flag turned on
- run the prometheus_example

**What is the expected behavior?**
What did you expect to see?
- Connection to my prometheus docker service, with metrics pushed in

**What is the actual behavior?**
What did you see instead?
- program crashes, outputting: `null context when constructing CivetServer. Possible problem binding to port.`

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1903

## Changes

Please provide a brief description of the changes here.

- Handle exception thrown by CivetServer (used by prometheus-cpp) if the port to listen is already used.
- Update documentation for Prometheus example (remove reference of PeriodicPushMetricReader) as per prometheus design changes in #1953.
- Change default Prometheus listening port to 9464 in example.

It's difficult to add unit-test to simulate port usage. So tested changes as below:

Step 1: Start a http server at particular port (say 8000):
```bash
$python3 -m http.server --cgi 8000
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

Step 2: Try running Prometheus example to invoke Prometheus exporter on this used port 8000:
```bash
$ ./prometheus_example all localhost:8000
PrometheusExporter example program running ...
[Error] File: /<path>/opentelemetry-cpp/exporters/prometheus/src/exporter.cc:26 [Prometheus Exporter] Can't initialize prometheus exposer with endpoint: localhost:8000
Error: null context when constructing CivetServer. Possible problem binding to port.
...
[Warning] File: /<path>/opentelemetry-cpp/sdk/src/metrics/metric_reader.cc:47 MetricReader::Shutdown - Cannot invoke shutdown twice!
$
```
This fails gracefully.

Step 3: Try running Prometheus example to invoke Prometheus exporter on some unused port (say 8001):
```bash
$ ./prometheus_example all localhost:8001
PrometheusExporter example program running ...
...
$
```
This is successful.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: exporters/prometheus/src/collector.cc [hunk 1]
```diff
@@ -27,6 +28,9 @@ std::vector<prometheus_client::MetricFamily> PrometheusCollector::Collect() cons
 {
   if (reader_->IsShutdown())
   {
+    OTEL_INTERNAL_LOG_WARN(
+        "[Prometheus Exporter] Collect: "
+        "Exporter is shutdown, cann't invoke collect operation.");
```
Comment (marcalff) [inline exporters/prometheus/src/collector.cc:33]: nit: can not

**Review by marcalff — APPROVED** [review]
LGTM, setting the exporter to shutdown looks like the best solution.

**Review by esigo — APPROVED** [review]
LGTM
Thanks for the fix :)
