### PR TITLE
Fix global log handle symbols when using dlopen

### LINKED ISSUE #1409: GlobalLogHandler::GetLogHandler() singleton is not unique.
Greetings.

The title is correct.

In my application, the code is calling:

(1) `GlobalLogHandler::SetLogHandler()`, to set a custom handler

(2) `OTEL_INTERNAL_LOG_XXX()`, to print internal logs.

These calls produce logs in the custom handler, as expected so far.

But then, later:

(3) `OTEL_INTERNAL_LOG_XXX()` calls from opentelemetry libraries
end up calling the default handler `DefaultLogHandler` instead of the custom
one, which defeats the purpose of a singleton `SetLogHandler()`.

Analysis:

`GlobalLogHandler::GetHandlerAndLevel()` is implemented inline in a header
file, not a .cc file.

When building static libraries, this "singleton" ends up in multiple
libraries:

```
malff@localhost.localdomain:lib64> pwd
/usr/local/lib64
malff@localhost.localdomain:lib64> for L in `ls libopentelemetry_*.a`; do echo $L; nm $L | c++filt | grep GlobalLogHandler::GetHandlerAndLevel; done
```

```
libopentelemetry_common.a
libopentelemetry_exporter_ostream_metrics.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_ostream_span.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_otlp_grpc.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_otlp_grpc_log.a
libopentelemetry_exporter_otlp_http.a
libopentelemetry_exporter_otlp_http_client.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_http_client_curl.a
libopentelemetry_metrics.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_otlp_recordable.a
libopentelemetry_proto.a
libopentelemetry_resources.a
libopentelemetry_trace.a
0000000000000000 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000000000 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000000000 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_version.a

```

Note, interestingly, how the `GlobalLogHandler::GetHandlerAndLevel()` code is
not part of `libopentelemetry_common.a`, but defined (not referenced) in every use instead.

(4)

`man nm` gives, for my platform and for `"u"`:

>            "u" The symbol is a unique global symbol.  This is a GNU extension to the standard set of
>                ELF symbol bindings.  For such a symbol the dynamic linker will make sure that in the
>                entire process there is just one symbol with this name and type in use.

I am willing to accept that the linker, when linking several `libopentelemetry_*.a` static libraries into a final binary, will resolve duplicates, making the singleton unique.

However, there is more to it.

Now with dynamic libraries:

```
malff@localhost.localdomain:lib64> pwd
/usr/local/lib64
malff@localhost.localdomain:lib64> for L in `ls libopentelemetry_*.so`; do echo $L; nm $L | c++filt | grep GlobalLogHandler::GetHandlerAndLevel; done
```

```
libopentelemetry_common.so
libopentelemetry_exporter_ostream_metrics.so
000000000023f788 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
000000000002da83 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
000000000023f760 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_ostream_span.so
0000000000308048 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
00000000000c8765 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000308020 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_otlp_grpc_log.so
libopentelemetry_exporter_otlp_grpc.so
00000000017a82e8 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
0000000000c1d273 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
00000000017a82c0 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_otlp_http_client.so
0000000000727688 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
00000000002ccd8f W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
0000000000727660 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_exporter_otlp_http.so
libopentelemetry_http_client_curl.so
libopentelemetry_metrics.so
00000000004646c8 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
00000000001b0a4f W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
00000000004646a0 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_otlp_recordable.so
libopentelemetry_resources.so
libopentelemetry_trace.so
00000000002e4a08 u guard variable for opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
00000000000b06d1 W opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()
00000000002e49e0 u opentelemetry::v1::sdk::common::internal_log::GlobalLogHandler::GetHandlerAndLevel()::handler_and_level
libopentelemetry_version.so
```

My reading of (4) is that the linker, when producing a -- **_single_** -- `opentelemetry_xyz.so` library, will ensure the symbol there is unique ... for this .so alone.

The linker is never given all the code at once, and can not enforce uniqueness for all the *.so libraries combined.

Looking further, at runtime: how is `dlopen()` supposed to reconcile uniqueness of a symbol, when defined in multiple *.so shared libraries ?

Note how the symbol is "W" (weak)

>            "W"
>            "w" The symbol is a weak symbol that has not been specifically tagged as a weak object
>                symbol.  When a weak defined symbol is linked with a normal defined symbol, the normal
>                defined symbol is used with no error.  When a weak undefined symbol is linked and the
>                symbol is not defined, the value of the symbol is determined in a system-specific
>                manner without error.  On some systems, uppercase indicates that a default value has
>                been specified.

This possibly explains why multiple instances of the same singleton are not reported as duplicate symbols.

I was not able to investigate if/how `dlopen()` resolves this, and whether there are indeed multiple instances of the singleton in the final loaded binary or not, but this is highly suspicious, and the behavior seen is consistent with duplicates.

Suggestions for a fix:

Abandon the idea of defining singleton in header files, use a *.cc file instead.

For `GlobalLogHandler::GetHandlerAndLevel()`,
implement this in `global_log_handler.cc`, and adjust makefiles accordingly.

Now, this raises the interesting questions of every other singleton defined in
header files, in particular:
- per signal provider singletons
- global propagator singletons
- internal spin locks singletons
- etc

For example:
- `trace::Provider::GetTracerProvider()`
- `trace::Provider::GetLock()`
are at risk of not being unique.

Please consider moving every singleton implementation in a *.cc file,
so it gets defined in only one library (.a or .so), not many.

A good home for these singletons can be `libopentelemetry_common.so`, possibly `libopentelemetry_version.so`

Regards.

### PR DESCRIPTION
**Pull request by owent**
Fixes #1409 

## Changes

+ Move implementation in `global_log_handler.h` to `global_log_handler.cc`

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: sdk/src/common/BUILD [hunk 1]
```diff
@@ -27,6 +27,18 @@ cc_library(
...
+cc_library(
+    name = "global_log_handler",
+    srcs = [
+        "global_log_handler.cc",
+    ],
+    deps = [
+        "//api",
+        "//sdk:headers",
+    ],
+)
```
Comment (marcalff) [inline sdk/src/common/BUILD:44]: I am not familiar with BAZEL, and I am confused by the build script here.

The bazel build defines two libraries, "random" and "global_log_handler", while the CMake build defines only one library, named "opentelemetry_common"

This is a pre existing issue, but how come file random.cc is compiled in library "random" with bazel, and "opentelemetry_common" with CMake ?

I would expect both build to produce the same libraries with the same name, and put the same *.cc code in the same *.so library.

File: sdk/src/common/global_log_handler.cc [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+  }
+  output_s << std::endl;
+  // TBD - print attributes
+  std::cout << output_s.str();  // thread safe.
+}
+
+std::pair<nostd::shared_ptr<LogHandler>, LogLevel> &GlobalLogHandler::GetHandlerAndLevel() noexcept
+{
+  static std::pair<nostd::shared_ptr<LogHandler>, LogLevel> handler_and_level{
+      nostd::shared_ptr<LogHandler>(new DefaultLogHandler), LogLevel::Warning};
```
Comment (marcalff) [inline sdk/src/common/global_log_handler.cc:64]: The singleton is in the *.cc file now, great.

As a side note, I reviewed every occurrence of the `static` keyword in every header file under sdk/include.

There are a few other static variables used, but none of them are required to be unique, so the scope of the fix is really narrowed down to this one alone, `handler_and_level` in `GlobalLogHandler::GetHandlerAndLevel()`.

**Review by marcalff — COMMENTED** [review]
Thanks @owent for implementing a fix.

For singletons in the `SDK`, I think we all agree this is the way to go.

See questions on `Bazel` vs `CMake`.

Regards.

File: sdk/src/common/global_log_handler.cc [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+  {
+    output_s << "File: " << file << ":" << line;
+  }
+  if (msg != nullptr)
+  {
+    output_s << msg;
+  }
+  output_s << std::endl;
+  // TBD - print attributes
+  std::cout << output_s.str();  // thread safe.
```
[the remark this answers is not in the document]
Comment (lalitb) [reply sdk/src/common/global_log_handler.cc:58]: Agree, the method is supposed to be empty.

File: sdk/src/common/BUILD (hunk 1 above)
Comment (lalitb) [reply sdk/src/common/BUILD:44]: Agree, though not related to this PR, it would be good to have both cmake and bazel produce a consistent set of libraries.

File: exporters/jaeger/BUILD [hunk 4]
```diff
@@ -180,6 +180,7 @@ cc_library(
     tags = ["jaeger"],
     deps = [
         ":jaeger_exporter",
+        "//sdk/src/common:global_log_handler",
```
Comment (lalitb) [inline exporters/jaeger/BUILD:183]: Do we need to add this for other exporters too. Eg, zipkin exporter includes sdk_config.h, which further includes global_log_handler.

File: sdk/src/common/BUILD (hunk 1 above)
Comment (owent) [reply sdk/src/common/BUILD:44]: Agree too. We can raise another PR to produce a consistent set of libraries between bazel and cmake.There are more libraries names need be reviewed.

File: exporters/jaeger/BUILD (hunk 4 above)
Comment (owent) [reply exporters/jaeger/BUILD:183]: Exporters shoud denpend on `//sdk/src/logs` , `//sdk/src/metrics` or `//sdk/src/trace` , which already depend `//sdk/src/common:global_log_handler`

File: sdk/src/common/global_log_handler.cc (hunk 2 above)
Comment (owent) [reply sdk/src/common/global_log_handler.cc:64]: Yes, we can raise another issue to move all static variables into `*.cc`, it's still a waste of memory.

File: sdk/src/common/global_log_handler.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (owent) [reply sdk/src/common/global_log_handler.cc]: Thanks and fixed.

**Review by lalitb — APPROVED** [review]
LGTM. Thanks for the fix.

File: sdk/src/common/global_log_handler.cc (hunk 2 above)
Comment (marcalff) [reply sdk/src/common/global_log_handler.cc:50]: Agree, filed issue #1429 then.

**Comment by lalitb** [comment]
@owent  - Can you please rebase this, to enable merge.

**Review by ThomsonTan — APPROVED** [review]

**Comment by owent** [comment]
> @owent - Can you please rebase this, to enable merge.

Done
