### PR TITLE
[API] Parse baggage value as spec compliant

### LINKED ISSUE #3754: Values with colon in baggage header are not parsed as valid
**Describe your environment** MacOS, Bazel, latest

**Steps to reproduce**

```c++
auto baggage_value = "field=foo:bar";  // Note the colon ":"
auto baggage = opentelemetry::baggage::Baggage::FromHeader(baggage_value);

std::string field_value;
baggage->GetValue("field", field_value);

std::cout << "Field value: " << field_value << std::endl;
```

**What is the expected behavior?**
Field value is parsed as `foo:bar`.

**What is the actual behavior?**
Field value is empty

**Additional context**
If the field value is passed as URL encoded, it seems to work correctly `field=foo%3Abar`.

I'm also curious if this is indeed intended behaviour?

### PR DESCRIPTION
**Pull request by ThomsonTan**
Fixes #3754 

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: api/include/opentelemetry/baggage/baggage.h [hunk 1]
```diff
@@ -274,8 +274,8 @@ class OPENTELEMETRY_EXPORT Baggage
       {
         ret.push_back(' ');
       }
-      else if (std::isalnum(str[i]) || str[i] == '-' || str[i] == '_' || str[i] == '.' ||
-               str[i] == '~')
+      else if (str[i] >= ' ' && str[i] <= '~' && str[i] != '"' && str[i] != ',' && str[i] != ';' &&
+               str[i] != '\\')
```
Comment (marcalff) [inline api/include/opentelemetry/baggage/baggage.h]: Several comments:

1) Please add a comment that points to the spec: https://www.w3.org/TR/baggage/#definition, to explain what this is about.

2) Per the spec, a space (20) should be illegal. the test `str[i] >= ' '` seems broken.

3) Consider using parenthesis and comments for better readability, as in

```
if (   (str[i] >= '!' ) /* 21 */
    && (str[i] <= '~' ) /* 7E */
    && (str[i] != '"') /* 22 */
    && (str[i] != ',') /* 2C */
    && (str[i] != ';') /* 3B */
    && (str[i] != '\\')) /* 5C */
```
