### PR TITLE
[BUILD] Fix elasticsearch exporter json compatibility

### LINKED ISSUE #3312: Elasticsearch exporter build fails with nlohmann_json version 3.10.5 and older
**Describe your environment** 
main at b4328c0bc1
Ubuntu 22.04 github runner (setup with `./ci/setup_goolgletest.sh`)

**Steps to reproduce**
Set up a Ubuntu 22.04 runner
Build with WITH_ELASTICSEARCH=ON 

**What is the expected behavior?**
Build succeeds

**What is the actual behavior?**
Build fails

```
/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/elasticsearch/src/es_log_recordable.cc:35:9: error: no match for ‘operator=’ (operand types are ‘nlohmann::basic_json<>’ and ‘const opentelemetry::v1::nostd::span<const unsigned char>’)
   35 |     *j_ = u;
      |     ~~~~^~~
In file included from /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/elasticsearch/src/es_log_recordable.cc:8:
/usr/include/nlohmann/json.hpp:1926:17: note: candidate: ‘nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>& nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::operator=(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]’
 1926 |     basic_json& operator=(basic_json other) noexcept (
      |                 ^~~~~~~~
/usr/include/nlohmann/json.hpp:1926:38: note:   no known conversion for argument 1 from ‘const opentelemetry::v1::nostd::span<const unsigned char>’ to ‘nlohmann::basic_json<>’
 1926 |     basic_json& operator=(basic_json other) noexcept (
      |                           ~~~~~~~~~~~^~~~~
make[2]: *** [exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/build.make:93: exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/src/es_log_recordable.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9780: exporters/elasticsearch/CMakeFiles/opentelemetry_exporter_elasticsearch_logs.dir/all] Error 2
```

**Additional context**
The ubuntu runners install `nlohmann-json3-dev` with `ci/setup_googletest.sh` The Elasticsearch exporter can build against the package on Ubuntu 24.04 (version 3.11.3) but fails on Ubuntu 22.04 (version 3.10.5) and older.

### PR DESCRIPTION
**Pull request by dbarker**
Fixes #3312

The system package of nlohmann_json is version 3.10.5 on Ubuntu 22.04. 

## Changes
- Add a template specialization of the `json_assign_visitor` to handle `nostd::span` attribute values. 
- Switch one runner that builds the elastic search exporter (runs ./ci/do_ci.sh cmake.test) to Ubuntu 22.04 and CXX_STANDARD=17

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

File: exporters/elasticsearch/src/es_log_recordable.cc [hunk 1]
```diff
@@ -23,17 +23,27 @@
 
 namespace nlohmann
 {
-template <class T>
+template <typename T>
```
Comment (owent) [inline exporters/elasticsearch/src/es_log_recordable.cc:26]: Why change it to `typename`? Using `class` is preferred in some practices. If we switch to `typename`, all template declarations should be updated for consistency.

**Review by owent — CHANGES_REQUESTED** [review]

File: exporters/elasticsearch/src/es_log_recordable.cc (hunk 1 above)
Comment (dbarker) [reply exporters/elasticsearch/src/es_log_recordable.cc]: Good point. Changing the least number of lines is better. Using typename is just a habit for me. Changed back to class here.

Comment (marcalff) [reply exporters/elasticsearch/src/es_log_recordable.cc]: Resolved, @owent PTAL.

**Review by owent — APPROVED** [review]
LGTM, thanks.

**Review by ThomsonTan — APPROVED** [review]
