### PR TITLE
[API] Return NoopLogRecord from NoopLogger

### LINKED ISSUE #2656: [API] NoopLogger causes segfault
**Describe your environment** v1.14.2

**Steps to reproduce**
```
#include "opentelemetry/logs/provider.h"

int main(int argc, char* argv[]) {
  auto logs_provider = opentelemetry::v1::logs::Provider::GetLoggerProvider();
  auto logger = logs_provider->GetLogger("test");
  auto sample = logger->CreateLogRecord();
  sample->SetAttribute("some key", "some value");
  logger->EmitLogRecord(std::move(sample));
  return 0;
}
```

**What is the expected behavior?**
Program should run successfully.

**What is the actual behavior?**
SEGV at `sample->SetAttribute` because `sample` is null.

**Additional context**
https://github.com/open-telemetry/opentelemetry-cpp/blob/da8e377be51edadad514d31c58e0ce7a2eb1b05e/api/include/opentelemetry/logs/noop.h#L37

The NoopLogger is supposed to return __usable__ objects, not a `nullptr`.

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #2656

Based on PR contribution #2662 from @yurishkuro

## Changes

Please provide a brief description of the changes here.

NoopLogger was incorrectly returning nullptr, causing segfaults in client code. After this change it returns a dummy no-op log record.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [X] Unit tests have been added
* [X] Changes in public API reviewed

### CODE REVIEW

**Comment by yurishkuro** [comment]
> Based on PR contribution #2662 from @yurishkuro

Nit: I personally don't care but when you have new contributors (e.g. someone just starting in oss) I always try to preserve their own commits, e.g. by branching off of their branch, so that they get proper credit as contributors.  E.g. GitHub shows all authors:
image

**Review by yurishkuro — APPROVED** [review]

**Comment by marcalff** [comment]
> > Based on PR contribution #2662 from @yurishkuro
> 
> Nit: I personally don't care but when you have new contributors (e.g. someone just starting in oss) I always try to preserve their own commits, e.g. by branching off of their branch, so that they get proper credit as contributors.

Good point, I need to improve my github skills to do that.

Now that 2662 is closed, the branch is deleted so I can't reopen it to use it.

@yurishkuro Feel like submitting a 1 line change using the web interface, to get the the git credits fixed ?

**Comment by marcalff** [comment]
Do not merge label, waiting for additional commit.

Ready for review.

**Comment by yurishkuro** [comment]
> Feel like submitting a 1 line change using the web interface, to get the git credits fixed ?

no it's fine, like I said, I don't care, it was more of a general comment on a nicer way of accepting contributions.

**Comment by marcalff** [comment]
> > Feel like submitting a 1 line change using the web interface, to get the git credits fixed ?
> 
> no it's fine, like I said, I don't care, it was more of a general comment on a nicer way of accepting contributions.

Thanks. Point taken.

File: api/include/opentelemetry/logs/noop.h [hunk 1]
```diff
@@ -34,11 +34,39 @@ class NoopLogger final : public Logger
 public:
   const nostd::string_view GetName() noexcept override { return "noop logger"; }
 
-  nostd::unique_ptr<LogRecord> CreateLogRecord() noexcept override { return nullptr; }
+  nostd::unique_ptr<LogRecord> CreateLogRecord() noexcept override
+  {
+    /*
+     * Do not return memory shared between threads,
+     * a new + delete for each noop record can not be avoided,
```
Comment (marcalff) [inline api/include/opentelemetry/logs/noop.h:41]:
```suggestion
     * a `new` + `delete` for each noop record can not be avoided,
```

**Comment by marcalff** [comment]
To add to change set upon merge:

    Co-authored-by: Yuri Shkuro <yurishkuro@users.noreply.github.com>

File: api/include/opentelemetry/logs/noop.h [hunk 2]
```diff
@@ -34,11 +34,39 @@ class NoopLogger final : public Logger
...
 
-  nostd::unique_ptr<LogRecord> CreateLogRecord() noexcept override { return nullptr; }
+  nostd::unique_ptr<LogRecord> CreateLogRecord() noexcept override
+  {
+    /*
+     * Do not return memory shared between threads,
+     * a `new` + `delete` for each noop record can not be avoided,
+     * due to the semantic of unique_ptr.
+     */
+    return nostd::unique_ptr<LogRecord>(new NoopLogRecord());
```
Comment (lalitb) [inline api/include/opentelemetry/logs/noop.h:44]: Not sure if I fully understand the issue, but can we instead return a unique_ptr to static NoopLogRecord instance, with a custom  deleter which does nothing. This will ensure that the static instance is not deleted when the unique_ptr goes out of scope.
This way, if the LoggerProvider is not configured in SDK, and instrumented library won't do any allocation with every log call.

**Review by lalitb — CHANGES_REQUESTED** [review]
For - https://github.com/open-telemetry/opentelemetry-cpp/pull/2668#discussion_r1603695457

I see a perf concern here if the SDK is not configured.

File: api/include/opentelemetry/logs/noop.h (hunk 2 above)
Comment (yurishkuro) [reply api/include/opentelemetry/logs/noop.h:44]: this was explored in https://github.com/open-telemetry/opentelemetry-cpp/pull/2662 and did not work, unique_ptr damages vtable of a static instance.

**Comment by yurishkuro** [comment]
> I see a perf concern here if the SDK is not configured.

I'll take perf concern over segfault. Right now the noop implementation is simply not usable.

File: api/test/logs/logger_test.cc [hunk 3]
```diff
@@ -28,9 +28,11 @@ TEST(Logger, GetLoggerDefault)
   auto lp = Provider::GetLoggerProvider();
   const std::string schema_url{"https://opentelemetry.io/schemas/1.11.0"};
   auto logger = lp->GetLogger("TestLogger", "opentelelemtry_library", "", schema_url);
-  auto name   = logger->GetName();
   EXPECT_NE(nullptr, logger);
+  auto name   = logger->GetName();
```
Comment (ThomsonTan) [inline api/test/logs/logger_test.cc:32]: nit, check name before `logger->CreateLogRecord`.

File: sdk/src/logs/logger.cc [hunk 4]
```diff
@@ -33,12 +33,6 @@ const nostd::string_view Logger::GetName() noexcept
 
 nostd::unique_ptr<opentelemetry::logs::LogRecord> Logger::CreateLogRecord() noexcept
 {
-  // If this logger does not have a processor, no need to create a log recordable
-  if (!context_)
```
Comment (ThomsonTan) [inline sdk/src/logs/logger.cc:37]: Is context_ always not null?

File: api/include/opentelemetry/logs/noop.h (hunk 2 above)
Comment (lalitb) [reply api/include/opentelemetry/logs/noop.h:44]: ok thanks for the link. Yes agree multiple delete calls from different threads would be an issue.

**Comment by lalitb** [comment]
> I'll take perf concern over segfault. Right now the noop implementation is simply not usable.

Yes segfault was indeed a bug to be fixed.  The fix is unfortunately adding a perf overhead for instrumented libraries when the logging is not enabled, which is not good. Not an issue with this PR, more of the constraint added by the design. I will create a tracking issue for this to be handled separately.

**Review by lalitb — APPROVED** [review]

File: sdk/src/logs/logger.cc (hunk 4 above)
Comment (marcalff) [reply sdk/src/logs/logger.cc:37]: It is never null, a context is always created when building a logger provider.

File: api/test/logs/logger_test.cc (hunk 3 above)
Comment (marcalff) [reply api/test/logs/logger_test.cc:32]: Thanks, fixed.
