### PR TITLE
[CI] Build failures with ABSEIL 20240116 and CMAKE 3.30

### LINKED ISSUE #2998: [CI] Build failures with ABSEIL 20240116 and CMAKE 3.30
CI started to fail for this build:

```
CI / CMake test (with abseil) (pull_request) 
```

The failure is in:

```
./ci/install_abseil.sh
```

Failure:

```
-- Configuring done (0.5s)
CMake Error at CMake/AbseilHelpers.cmake:317 (target_link_libraries):
  The link interface of target "test_allocator" contains:

    GTest::gmock

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  absl/container/CMakeLists.txt:206 (absl_cc_library)


CMake Generate step failed.  Build files cannot be regenerated correctly.
-- Generating done (0.2s)
Error: Process completed with exit code 1.
```

To investigate, I suspect a regression caused by the new image `Version: 20240708.1.0`:

```
Current runner version: '2.317.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20240708.1.0
```

Previous runs that builds properly:

```
Current runner version: '2.317.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20240701.1.0
```

See related:

* https://github.com/actions/runner-images/pull/10191

To investigate, CMake was upgraded.

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #2998

## Changes

Please provide a brief description of the changes here.

* Backported a fix for abseil issue 1536, applied to abseil-cpp 20240116
* Fixed the CI format to ignore `*.patch` files

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]

File: ci/install_abseil.sh [hunk 1]
```diff
@@ -22,6 +24,41 @@ if [ ! -z "${CXX_STANDARD}" ]; then
...
+#   https://github.com/abseil/abseil-cpp/pull/1536
+#
+# Applying fix from abseil commit 779a3565ac6c5b69dd1ab9183e500a27633117d5
+#
+# TODO(marcalff) Cleanup once abseil is upgraded to the next LTS
+
+
+if [ "${ABSEIL_CPP_VERSION}" = "20240116.1" ] || [ "${ABSEIL_CPP_VERSION}" = "20240116.2" ]; then
+  echo "Patching abseil"
+  patch -p1 < ${TOPDIR}/ci/fix-abseil-cpp-issue-1536.patch
```
Comment (ThomsonTan) [inline ci/install_abseil.sh:57]: Could local build still be broken if this fix is targeting CI?

Comment (marcalff) [reply ci/install_abseil.sh:57]: Someone installing abseil-cpp 20240116 from source and building with cmake 3.30 will have a build failure, yes.

Not something we can do anything about.
