### PR TITLE
[SDK] Fix crash in `PeriodicExportingMetricReader`.

### LINKED ISSUE #2982: [EXPORTER] Spurious crash when using `PeriodicExportingMetricReader` and timeout.
**Describe your environment**

OS: Linux
Compiler: gcc 4.8.5

**Additional context**

Stackrace of corefile:

```bash
(gdb) bt
#0  0x00007f75ddb24387 in raise () from /lib64/libc.so.6
#1  0x00007f75ddb25a78 in abort () from /lib64/libc.so.6
#2  0x00007f75de21ea95 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f75de21ca06 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f75de21b9b9 in ?? () from /lib64/libstdc++.so.6
#5  0x00007f75de21c624 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007f75e9a928e3 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007f75e9a92c7b in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#8  0x00007f75de21cc46 in __cxa_throw () from /lib64/libstdc++.so.6
#9  0x00007f75de271f30 in std::__throw_system_error(int) () from /lib64/libstdc++.so.6
#10 0x00007f75de2730f8 in std::thread::join() () from /lib64/libstdc++.so.6
#11 0x00007f75df2e420b in __pthread_once_slow () from /lib64/libpthread.so.0
#12 0x00007f75de21abd7 in ?? () from /lib64/libstdc++.so.6
#13 0x00007f75de21acc4 in std::__future_base::_Async_state_common::~_Async_state_common() () from /lib64/libstdc++.so.6
#14 0x00007f75da6487f8 in std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>::_Async_state_impl (__fn=..., 
    this=0x7f75cca00018) at /usr/include/c++/4.8.2/future:1495
#15 __gnu_cxx::new_allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >::construct<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (this=<optimized out>, __p=0x7f75cca00018) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
#16 std::allocator_traits<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> > >::_S_construct<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., __p=0x7f75cca00018) at /usr/include/c++/4.8.2/bits/alloc_traits.h:254
#17 std::allocator_traits<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> > >::construct<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., __p=0x7f75cca00018) at /usr/include/c++/4.8.2/bits/alloc_traits.h:393
#18 std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u>::_Sp_counted_ptr_inplace<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., this=0x7f75cca00000) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:399
#19 __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u> >::construct<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u>, const std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (this=<synthetic pointer>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
#20 std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u> > >::_S_construct<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u>, const std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=<synthetic pointer>..., __p=<optimized out>) at /usr/include/c++/4.8.2/bits/alloc_traits.h:254
#21 std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u> > >::construct<std::_Sp_counted_ptr_inplace<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, (__gnu_cxx::_Lock_policy)2u>, const std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=<synthetic pointer>..., __p=<optimized out>) at /usr/include/c++/4.8.2/bits/alloc_traits.h:393
#22 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., this=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:502
#23 std::__shared_ptr<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, (__gnu_cxx::_Lock_policy)2u>::__shared_ptr<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., this=<optimized out>, __tag=...) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:957
#24 std::shared_ptr<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >::shared_ptr<std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__a=..., __tag=..., this=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr.h:316
#25 std::allocate_shared<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::allocator<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void> >, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::Collec--Type <RET> for more, q to quit, c to continue without paging--
tAndExportOnce()::__lambda11()> > (__a=...) at /usr/include/c++/4.8.2/bits/shared_ptr.h:598
#26 std::make_shared<std::__future_base::_Async_state_impl<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()>, void>, std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > () at /usr/include/c++/4.8.2/bits/shared_ptr.h:614
#27 std::__future_base::_S_make_async_state<std::_Bind_simple<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11()> > (__fn=...) at /usr/include/c++/4.8.2/future:1525
#28 std::async<opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce()::__lambda11> (__policy=std::launch::async, __fn=...) at /usr/include/c++/4.8.2/future:1538
#29 opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::CollectAndExportOnce (this=this@entry=0x7f75d760c000)
    at /data/devops/workspace/p-4943d876cb734a609b55ad5c740c36ff/src/pool/0/server/main/third_party/packages/opentelemetry-cpp-v1.15.0/sdk/src/metrics/export/periodic_exporting_metric_reader.cc:89
#30 0x00007f75da648a38 in opentelemetry::v1::sdk::metrics::PeriodicExportingMetricReader::DoBackgroundWork (this=0x7f75d760c000)
    at /data/devops/workspace/p-4943d876cb734a609b55ad5c740c36ff/src/pool/0/server/main/third_party/packages/opentelemetry-cpp-v1.15.0/sdk/src/metrics/export/periodic_exporting_metric_reader.cc:55
#31 0x00007f75de273340 in ?? () from /lib64/libstdc++.so.6
#32 0x00007f75df2e5ea5 in start_thread () from /lib64/libpthread.so.0
#33 0x00007f75ddbecb0d in clone () from /lib64/libc.so.6
```

Datas in Frame 13-14:

```bash
(gdb) f 13
#13 0x00007f7c4ddb8cc4 in std::__future_base::_Async_state_common::~_Async_state_common() () from /lib64/libstdc++.so.6
(gdb) p _M_thread
No symbol "_M_thread" in current context.
(gdb) f 14
#14 0x00007f7c4a1ebc93 in _Async_state_impl (__fn=<unknown type in /data/home/user00/tgf-server/d-8/tgf/matchsvr/bin/../../lib64/6689e6af/lib64/libopentelemetry_metrics.so, CU 0x3cc73e, DIE 0x415b2f>, this=0x7f7acd401018)
    at /usr/include/c++/4.8.2/future:1495
1495          : _M_result(new _Result<_Res>()), _M_fn(std::move(__fn))
(gdb) p _M_thread
$9 = {_M_id = {_M_thread = 0}}
(gdb) p _M_once
$10 = {_M_once = 1}
(gdb) p _M_result
$11 = std::unique_ptr<std::__future_base::_Result<void>> containing 0x0
(gdb)
```

Codes in Frame 13-14:

```cpp
  class __future_base::_Async_state_common : public __future_base::_State_base
  {
  protected:
#ifdef _GLIBCXX_ASYNC_ABI_COMPAT
    ~_Async_state_common();
#else
    ~_Async_state_common() = default;
#endif

    // Allow non-timed waiting functions to block until the thread completes,
    // as if joined.
    virtual void _M_run_deferred() { _M_join(); }

    void _M_join() { std::call_once(_M_once, &thread::join, ref(_M_thread)); }

    thread _M_thread;
    once_flag _M_once;
  };

  template<typename _BoundFn, typename _Res>
    class __future_base::_Async_state_impl final
    : public __future_base::_Async_state_common
    {
    public:
      explicit
      _Async_state_impl(_BoundFn&& __fn)
      : _M_result(new _Result<_Res>()), _M_fn(std::move(__fn))
      {
        _M_thread = std::thread{ [this] {
          _M_set_result(_S_task_setter(_M_result, _M_fn));
        } };
      }

      ~_Async_state_impl() { _M_join(); }

    private:
      typedef __future_base::_Ptr<_Result<_Res>> _Ptr_type;
      _Ptr_type _M_result;
      _BoundFn _M_fn;
    };
```

It may relate to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54297 and https://stackoverflow.com/questions/28604461/using-c11-futures-nested-calls-of-stdasync-crash-compiler-standard-library.

### PR DESCRIPTION
**Pull request by owent**
Fixes #2982 

## Changes

+ Keep the lifetimes of `PeriodicExportingMetricReader` and a local variable when calling `std::async`.

@lalitb @marcalff  Just wondering why we use `std::async(std::launch::async, ...)` here? It will create a lot of thread when timeout occurs frequently, and it will use a lot of resource and slow down the whole application then.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 1]
```diff
@@ -89,19 +89,26 @@ void PeriodicExportingMetricReader::DoBackgroundWork()
...
-      }
-      this->exporter_->Export(metric_data);
-      return true;
-    });
+  std::shared_ptr<std::atomic<bool>> cancel_export_for_timeout =
+      std::make_shared<std::atomic<bool>>(false);
+  auto keep_lifetime = shared_from_this();
+
+  auto future_receive = std::async(std::launch::async, [keep_lifetime, cancel_export_for_timeout] {
+    static_cast<PeriodicExportingMetricReader *>(keep_lifetime.get())
```
Comment (lalitb) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:97]: do  we need the typecast, or can we do:
`keep_lifetime->Collect([keep_lifetime, ...](` ?

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 2]
```diff
@@ -89,19 +89,26 @@ void PeriodicExportingMetricReader::DoBackgroundWork()
...
+        ->Collect([keep_lifetime, cancel_export_for_timeout](ResourceMetrics &metric_data) {
+          if (*cancel_export_for_timeout)
```
Comment (lalitb) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:99]:
```suggestion
          if (cancel_export_for_timeout->load())
```

nit -just for readibility.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 3]
```diff
@@ -89,19 +89,26 @@ void PeriodicExportingMetricReader::DoBackgroundWork()
...
+          {
+            OTEL_INTERNAL_LOG_ERROR(
+                "[Periodic Exporting Metric Reader] Collect took longer configured time: "
+                << static_cast<PeriodicExportingMetricReader *>(keep_lifetime.get())
+                       ->export_timeout_millis_.count()
```
Comment (lalitb) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:104]: nit - same as earlier "do we need the typecast ?"

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 4]
```diff
@@ -111,7 +118,7 @@ bool PeriodicExportingMetricReader::CollectAndExportOnce()
     status = future_receive.wait_for(std::chrono::milliseconds(export_timeout_millis_));
     if (status == std::future_status::timeout)
     {
-      cancel_export_for_timeout = true;
+      *cancel_export_for_timeout = true;
```
Comment (lalitb) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:121]:
```suggestion
      cancel_export_for_timeout->store(true);
```

nit -just for readibility.

**Comment by lalitb** [comment]
> Just wondering why we use std::async(std::launch::async, ...) here? It will create a lot of thread when timeout occurs frequently, and it will use a lot of resource and slow down the whole application then.

@owent  Can you please elaborate the issue? As I understand, we won't start a new collect if the previous is already ongoing. So timeout, shouldn't create a new thread.

**Comment by lalitb** [comment]
Thanks for the fix. Some nit comments, but in general looks good.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 3 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc:104]: `keep_lifetime` is `std::shared_ptr<MetricReader>` but we need `PeriodicExportingMetricReader*` here.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 1 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc]: `keep_lifetime->Collect([keep_lifetime, ...](` is enough here. Thanks and fixed.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 2 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc]: Thanks and fixed.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 4 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc]: Thanks and fixed.

**Comment by owent** [comment]
> > Just wondering why we use std::async(std::launch::async, ...) here? It will create a lot of thread when timeout occurs frequently, and it will use a lot of resource and slow down the whole application then.
> 
> @owent Can you please elaborate the issue? As I understand, we won't start a new collect if the previous is already ongoing. So timeout, shouldn't create a new thread.

The `future_receive` in this function will be dropped after `PeriodicExportingMetricReader::CollectAndExportOnce` when timeout.
And maybe the exporting is still running.In my understand, `PeriodicExportingMetricReader::DoBackgroundWork` will call `PeriodicExportingMetricReader::CollectAndExportOnce` sooner after previous timeout.

The coredump file of crashed process in my application show it has about 290+ threads.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 3 above)
Comment (lalitb) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc:104]: Can we instead make `PeriodicExportingMetricReader` inherit from `std::enable_shared_from_this<PeriodicExportingMetricReader>`, and remove for `MetricReader`, if this allows avoiding typecast.

```cpp
class PeriodicExportingMetricReader : public MetricReader, public std::enable_shared_from_this<PeriodicExportingMetricReader> {
    // ... rest of the class ...
};
```

**Review by lalitb — APPROVED** [review]
Thanks for the fix. LGTM with nit comments.

File: sdk/include/opentelemetry/sdk/metrics/metric_reader.h [hunk 5]
```diff
@@ -19,7 +20,7 @@ namespace metrics
 /**
  * MetricReader defines the interface to collect metrics from SDK
  */
-class MetricReader
+class MetricReader : public std::enable_shared_from_this<MetricReader>
```
Comment (marcalff) [inline sdk/include/opentelemetry/sdk/metrics/metric_reader.h:23]: See alternate solution.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 6]
```diff
@@ -89,19 +89,26 @@ void PeriodicExportingMetricReader::DoBackgroundWork()
...
-            "[Periodic Exporting Metric Reader] Collect took longer configured time: "
-            << export_timeout_millis_.count() << " ms, and timed out");
-        return false;
-      }
-      this->exporter_->Export(metric_data);
-      return true;
-    });
+  std::shared_ptr<std::atomic<bool>> cancel_export_for_timeout =
+      std::make_shared<std::atomic<bool>>(false);
+  auto keep_lifetime = shared_from_this();
```
Comment (marcalff) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:94]: If I understand correctly, this code forces the use of a shared_ptr, and implicitly uses the shared_ptr internal reference counter to count how many exports are in flight.

Alternate solution:

* Implement a new member, `std::atomic<int> m_pending_exports`, to count how many exports are pending.
* When a new export starts, increment this counter
* When an export completes, decrement the counter
* In shutdown(), wait in a loop for the counter to reach 0

I think this will be better, with the following benefits:

* The code can check if exports are already pending before starting a new export, and raise an error, instead of piling up threads.
* The wait loop in shutdown can print warning messages with the current counter, so it is easier to debug, and understand that many exports are still in flight.
* This does not force `PeriodicExportingMetricReader` to become a shared_ptr

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc [hunk 7]
```diff
@@ -111,7 +118,7 @@ bool PeriodicExportingMetricReader::CollectAndExportOnce()
     status = future_receive.wait_for(std::chrono::milliseconds(export_timeout_millis_));
     if (status == std::future_status::timeout)
     {
-      cancel_export_for_timeout = true;
+      cancel_export_for_timeout->store(true, std::memory_order_release);
```
Comment (marcalff) [inline sdk/src/metrics/export/periodic_exporting_metric_reader.cc:121]: Independently of this PR (to discuss):

* The ``::Collect()` loop processes all instruments at once today.
* We could pass the cancel_export_for_timeout pointer to the collect method, so collect can check at each loop if the timeout already is passed.
* This will make collect more responsive, and abort sooner when a lot of metrics are defined.

Also:

* shutdown may need to signal to pending exports to stop.
* For this, the class `PeriodicExportingMetricReader` can keep a reference to the cancel_export_for_timeout pointers, and change them on shutdown, to notify exporter threads to stop

This will increase robustness, and prevent too many threads to run concurrently.

**Review by marcalff — CHANGES_REQUESTED** [review]
Thanks for the PR.

See comments, for a proposed different implementation.

Marking as request changes for now to discuss it,
will revise the review if it turns out to be not practical.

**Comment by lalitb** [comment]
To clarify, my approval assumes this PR fixes the crash by keeping PeriodicExportingMetricReader alive during async ops, and thread explosion during timeouts will be tracked/addressed separately.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 3 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc:104]: Good point, it's a better solution for just a temporary fixes.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 7 above)
Comment (owent) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc:118]: Good point. But can we implement it in another PR? This is just a quick fix for crash.

Comment (marcalff) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc:118]: Yes, definitively in another PR.

File: sdk/include/opentelemetry/sdk/metrics/metric_reader.h [hunk 8]
```diff
@@ -5,6 +5,7 @@
 
 #include <atomic>
 #include <chrono>
+#include <memory>
```
Comment (marcalff) [inline sdk/include/opentelemetry/sdk/metrics/metric_reader.h:8]: This line is no longer needed, now that the shared_from_this moved to the sub class.

Please note that the include-what-you-use build in CI now reports this:

```
[ 25%] Building CXX object sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/metric_reader.cc.o
Warning: include-what-you-use reported diagnostics:

/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/include/opentelemetry/sdk/metrics/metric_reader.h should add these lines:

/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/include/opentelemetry/sdk/metrics/metric_reader.h should remove these lines:
- #include <memory>  // lines 8-8

The full include-list for /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/include/opentelemetry/sdk/metrics/metric_reader.h:
#include <atomic>                                              // for atomic
#include <chrono>                                              // for micros...
#include "opentelemetry/nostd/function_ref.h"                  // for functi...
#include "opentelemetry/sdk/metrics/export/metric_producer.h"  // for Metric...
#include "opentelemetry/sdk/metrics/instruments.h"             // for Aggreg...
#include "opentelemetry/version.h"                             // for OPENTE...
```

Warnings are not enforced as failures (yet), which is why it passes.

File: sdk/src/metrics/export/periodic_exporting_metric_reader.cc (hunk 3 above)
Comment (marcalff) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc]: Ok, so to clarify expectations:

Is the `public std::enable_shared_from_this<PeriodicExportingMetricReader>` meant to be temporary, until a better solution is found ?

I do agree it fixes the immediate crash, so the code no longer keep a pointer to a local variable in dead memory.

Comment (marcalff) [reply sdk/src/metrics/export/periodic_exporting_metric_reader.cc]: Approving, assuming this is a temporary fix.

File: sdk/include/opentelemetry/sdk/metrics/metric_reader.h (hunk 8 above)
Comment (owent) [reply sdk/include/opentelemetry/sdk/metrics/metric_reader.h]: Thanks, some other IWYU problems are also fixed.

**Review by marcalff — CHANGES_REQUESTED** [review]
CI for this PR is consistently stuck, when executing the proto unit tests.

All tests are executed, but the workflow does not stop.

I suspect that some thread is still blocked, either in the unit tests or in the exporter itself, that prevents the process to cleanly stop.

This happens only for this PR, so it does not look like a general issue.

Please investigate.

Even if some code needs to wait on something that never happens, it is desirable to wait with a timeout and retry, printing something in the internal log in each loop, so the code is easier to troubleshoot if this happens again.

**Comment by owent** [comment]
> CI for this PR is consistently stuck, when executing the "exporter proto" CI unit tests.
> 
> All tests are executed, but the workflow does not stop.
> 
> I suspect that some thread is still blocked, either in the unit tests or in the exporter itself, that prevents the process to cleanly stop.
> 
> This happens only for this PR, so it does not look like a general issue.
> 
> Please investigate.
> 
> Even if some code needs to wait on something that never happens, it is desirable to wait with a timeout and retry, printing something in the internal log in each loop, so the code is easier to troubleshoot if this happens again.

Sorry, I'm too busy these days. I will continue this some timer later.

**Comment by owent** [comment]
> Thanks for the PR.
> 
> See comments, for a proposed different implementation.
> 
> Marking as request changes for now to discuss it, will revise the review if it turns out to be not practical.

I use another implementation to avoid some BUGs in STL. Please review it again.

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

Thanks also for the extra cleanup for include-what-you-use.
