### PR TITLE
Otlp http cmake build fail

### LINKED ISSUE #1132: Failed to build opentelemetry-cpp with OTLP HTTP exporter
**Describe your environment**
OS: Debian 10 
Release version: opentelemetry-cpp v1.1.0
Compiler: g++ 8.3.0

**Steps to reproduce**

> cmake ../ -DWITH_OTLP=ON -DWITH_OTLP_HTTP=ON -DBUILD_TESTING=OFF
>make -j

**What is the expected behavior?**
Builds successfully

**What is the actual behavior?**
The build failed with the following error
>opentelemetry-cpp/exporters/otlp/src/otlp_http_client.cc:292:40: error: cannot convert 'const string' {aka 'const std::__cxx11::basic_string<char>'} to 'const unsigned char*'
         google::protobuf::Base64Escape(bytes, &base64_value);

>opentelemetry-cpp/exporters/otlp/src/otlp_http_client.cc:31:58: note:   initializing argument 1 of 'int google::protobuf::Base64Escape(const unsigned char*, int, char*, int)'
 LIBPROTOBUF_EXPORT int Base64Escape(const unsigned char *src, int slen, char *dest, int szdest);

**Aditional Context**
It seems that the function Base64Escape was being called with the incorrect set of arguments. It was called with bytes, which is an `std::string` instead of a `const unsigned char *`.

### PR DESCRIPTION
**Pull request by esigo**
Fixes #1132 (issue)

## Changes

Please provide a brief description of the changes here.
Use proper [overload](https://github.com/protocolbuffers/protobuf/blob/29b3d01572d50c0e5bc0ab2eea32f9779c7576f4/src/google/protobuf/stubs/strutil.h#L854).
For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
LGTM. Just curious why build didn't fail in our CI env.

**Comment by esigo** [comment]
> LGTM. Just curious why build didn't fail in our CI env.

probably because of including `strutil.h`.

File: exporters/otlp/src/otlp_http_client.cc [hunk 1]
```diff
@@ -21,14 +21,15 @@
 #include "google/protobuf/stubs/common.h"
 
 #if defined(GOOGLE_PROTOBUF_VERSION) && GOOGLE_PROTOBUF_VERSION >= 3007000
+#  include "google/protobuf/stubs/stringpiece.h"
```
Comment (ThomsonTan) [inline exporters/otlp/src/otlp_http_client.cc:24]: Wondering why it is necessary to include stringpiece.h because `Base64Escape` is declared in `strutil.h`?

**Comment by ThomsonTan** [comment]
> > LGTM. Just curious why build didn't fail in our CI env.
> 
> probably because of including `strutil.h`.

CI is not failing probably because we are using a newer version of protobuf. The explicit declaration is only old protobuf versions.

File: exporters/otlp/src/otlp_http_client.cc (hunk 1 above)
Comment (esigo) [reply exporters/otlp/src/otlp_http_client.cc]: yeah thanks, removed it.

**Review by ThomsonTan — APPROVED** [review]
