### PR TITLE
Patches to enable Visual Studio 2015 - Update 2 support

### LINKED ISSUE #314: context::ContextValue cannot be compiled with Visual Studio 2015
`ContextValue` has been recently introduced in SDK. Unfortunately the two `nostd::shared_ptr<...>` variant members are failing to compile with Visual Studio 2015, due to issue in `nostd::variant` backport.

This code fails to compile:

```cpp
using ContextValue = nostd::variant<bool,
                                    int64_t,
                                    uint64_t,
                                    double,
                                    nostd::shared_ptr<trace::Span>,
                                    nostd::shared_ptr<trace::SpanContext>>;
```

with the following error:

```
1>c:\work\opentelemetry-cpp\api\include\opentelemetry\nostd\variant.h(168): error C2672: 'opentelemetry::v0::nostd::detail::visitation::base::make_farray': no matching overloaded function found
1>c:\work\opentelemetry-cpp\api\include\opentelemetry\nostd\variant.h(173): note: see reference to class template instantiation 'opentelemetry::v0::nostd::detail::visitation::base::make_fmatrix_impl<F,opentelemetry::v0::nostd::detail::base<opentelemetry::v0::nostd::detail::Trait::Available,bool,int64_t,uint64_t,double,opentelemetry::v0::nostd::shared_ptr<opentelemetry::v0::trace::Span>,opentelemetry::v0::nostd::shared_ptr<opentelemetry::v0::trace::SpanContext>> &>::impl<opentelemetry::v0::nostd::integer_sequence<std::size_t>,opentelemetry::v0::nostd::integer_sequence<std::size_t>>' being compiled
```

whereas a simpler definition of the variant that does not use `nostd::shared_ptr` - compiles successfully:
```cpp
using ContextValue = nostd::variant < bool, int64_t, uint64_t, double>;
```
The issue is in a way how `nostd::variant` backport handles complex objects. Primitive types are OK.

There could be a few alternative solutions to this issue:
- declare that we cannot support Visual Studio 2015
- declare that RuntimeContext API does not work with Visual Studio 2015
- simplify the implementation to avoid positioning complex objects on variant, possibly using `raw pointers` instead
- fix an issue in implementation of `nostd::detail::visitation::base`
- explore ability to substitute the `nostd::variant` with `absl::variant` ( somewhat related to #275 - ability to substitute `nostd` with alternate implementation )

### PR DESCRIPTION
**Pull request by maxgolov**
Fixes #314 . It does not yet add the build system for supporting vs2015 builds in CI, as it is quite involved (there is no GitHub Actions runner with preinstalled vs2015 and installing one may need some tweaking, and IS SLOW.. unless we cache some docker container image for that). Best we can do is deploy additional vs2015 community build tools. I'll cover CI for vs2015 in a separate PR. I verified the code locally with ETW exporter on Windows with Visual Studio 2015 - Update 2. It compiles and works well.

# Changes

- MPark variant that we use in the SDK is NOT compiling with Visual Studio 2015. Abseil Variant is compiling and working well with Visual Studio 2015 Update 2+. This visual studio version requirement is coming from Abseil itself, but it's a reasonable requirement. The solution is to add a build option `HAVE_ABSEIL_VARIANT` to compile with that one instead of MPark variant.

- Visual Studio 2015 secure development practices does not like `std::copy` and breaks the build. The fix is to replace the `std::copy` with bounds-checked implementation that uses `for-loop`

- Visual Studio 2015 does not like passing context by value. There is a build error related to alignment. Passing by const reference works.

I manually verified that the code compiles and works in Visual Studio 2015 with ETW exporter. I will cover full CI and other exporters (OTLP, Elastic, etc.) in a follow-up PR that would add Visual Studio 2015 to build loop.

### CODE REVIEW

File: api/include/opentelemetry/context/runtime_context.h [hunk 1]
```diff
@@ -275,7 +275,14 @@ class ThreadLocalContextStorage : public RuntimeContextStorage
       Context *temp = new Context[new_capacity];
       if (base_ != nullptr)
       {
-        std::copy(base_, base_ + old_size, temp);
+        // vs2015 does not like this construct considering it unsafe:
```
Comment (ThomsonTan) [inline api/include/opentelemetry/context/runtime_context.h:278]: Check Visual Studio 2015 compiler like via `_MSC_VER` to separate the workaround for it?

File: api/include/opentelemetry/nostd/absl/README.md [hunk 2]
```diff
@@ -0,0 +1,9 @@
+# Notes on Abseil Variant implementation
+
+This is a snapshot of Abseil Variant `absl::variant` from Abseil `v2020-03-03#8`.
```
Comment (ThomsonTan) [inline api/include/opentelemetry/nostd/absl/README.md:3]: As this PR includes some sources files form abseil, is it compatible with our current license?

File: api/include/opentelemetry/nostd/absl/README.md [hunk 3]
```diff
@@ -0,0 +1,9 @@
...
+
+This code is required to compile OpenTelemetry code in vs2015 because MPark Variant implementation is not compatible with vs2015.
+
+Build option `HAVE_ABSEIL_VARIANT` allows to enable the build with `absl::variant`, `absl::get` and `absl::visit` as defalt implementation for `nostd::` classes.
```
Comment (pyohannes) [inline api/include/opentelemetry/nostd/absl/README.md:7]: Is there a reason we have to ship two variant implementations? If `absl` is needed for VS2015 (and we decide we want to support that), can't we just generally use the `absl` implementation (instead of the MPark one)?

Comment (maxgolov) [reply api/include/opentelemetry/nostd/absl/README.md:7]: I'd like to take a two-staged approach. We should use Abseil everywhere, but I'd like to keep it under the build option right now until I fully test all existing exporters with it. Within the same OS class the ABI compatibility is retained irrespective of what implementation we take, e.g. Mpark works for Linux and Mac no problem. Whereas Abseil works for Windows. I want to send a follow-up PR that adds a build loop for Windows to switch over to Abseil for Variant. Then we can do this for Linux and Mac.

File: api/include/opentelemetry/nostd/absl/README.md (hunk 2 above)
Comment (maxgolov) [reply api/include/opentelemetry/nostd/absl/README.md:3]: Yes, it is the same license. Apache License v2.0. It is better than MPark in this regard. Removing MPark eventually, we can get rid of the Boost license requirement.

File: api/include/opentelemetry/context/runtime_context.h (hunk 1 above)
Comment (maxgolov) [reply api/include/opentelemetry/context/runtime_context.h:278]: Does `std::copy` itself perform a bounds checking? i.e. what if new temp size - `new_capacity` is less than the old capacity? Since it's a raw pointer, I think the old code had a problem.

**Review by ThomsonTan — APPROVED** [review]

File: api/include/opentelemetry/nostd/absl/README.md (hunk 3 above)
Comment (maxgolov) [reply api/include/opentelemetry/nostd/absl/README.md:7]: I think long-term before v1.0 GA we should switch to Abseil for variant. That'd be great for another reason: we can get rid of Boost license in our list of licenses because only MPark variant is Boost License, whereas Abseil is also Apache License v2.0 .. but I'd like to do this switch in a separate PR.

Comment (maxgolov) [reply api/include/opentelemetry/nostd/absl/README.md:7]: #68

Comment (maxgolov) [reply api/include/opentelemetry/nostd/absl/README.md:7]: #68

Comment (pyohannes) [reply api/include/opentelemetry/nostd/absl/README.md:7]: Makes sense. Can you add an additional issue for this (apart from the license one), otherwise this might be lost when just looking at issue titles.

I'd be fine with switching to absl as default, having MPark under a switch (then our CI pipeline would verify how it's working). However, I assume you expect changes to be necessary for it to work on Linux.

**Review by pyohannes — APPROVED** [review]
Approved, provided we work toward getting rid of the MPark `variant` implementation.

File: api/include/opentelemetry/nostd/absl/README.md (hunk 3 above)
Comment (lalitb) [reply api/include/opentelemetry/nostd/absl/README.md:7]: Have created an issue for this #572 , and assigned to @maxgolov . Feel free to update with relevant details on it.
