### PR TITLE
[CODE HEALTH] Fix clang-tidy narrowing-conversions warnings in tests

### LINKED ISSUE #3978: [CODE HEALTH] clang-tidy cppcoreguidelines-narrowing-conversions warnings in tests
clang-tidy reports the following warnings in tests

----

**cppcoreguidelines-narrowing-conversions** (8 warnings)

| File | Line | Message |
|---|---|---|
| `opentelemetry-cpp/exporters/otlp/test/otlp_metrics_serialization_test.cc` | 281 | narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/exporters/otlp/test/otlp_metrics_serialization_test.cc` | 311 | narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/exporters/otlp/test/otlp_metrics_serialization_test.cc` | 384 | narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/sdk/test/metrics/aggregation_test.cc` | 418 | narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/sdk/test/metrics/aggregation_test.cc` | 440 | narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/sdk/test/metrics/metric_test_stress.cc` | 98 | narrowing conversion from 'unsigned int' to signed type 'int' is implementation-defined |
| `opentelemetry-cpp/sdk/test/metrics/metric_test_stress.cc` | 163 | narrowing conversion from 'unsigned long' to signed type 'int64_t' (aka 'long') is implementation-defined |
| `opentelemetry-cpp/sdk/test/metrics/metric_test_stress.cc` | 168 | narrowing conversion from 'uint64_t' (aka 'unsigned long') to signed type 'int64_t' (aka 'long') is implementation-defined |

----
To reproduce locally run the following in the development container:

```
export CXX_STANDARD=14
./ci/do_ci.sh cmake.clang_tidy.test
```
The markdown report with unique errors can be generated locally after building with the `ci/create_clang_tidy_report.py` script.

### PR DESCRIPTION
**Pull request by mateenali66**
Fixes #3978

applied `static_cast` at the narrowing point in three test files:

- `exporters/otlp/test/otlp_metrics_serialization_test.cc` (3 sites) -- cast the `size_t` loop index when calling protobuf `data_points(int)` accessors.
- `sdk/test/metrics/aggregation_test.cc` (2 sites) -- cast `size_t max_buckets_` in the ternary branches where the result is assigned to `int`. kept the lvalue type as-is because `test_merge` lambda takes `int expected_max_buckets` and the values here are small test constants.
- `sdk/test/metrics/metric_test_stress.cc` (3 sites) -- cast `hardware_concurrency()` (unsigned) and the uint64_t bucket counts/totals when accumulating into `int64_t`.

also decremented clang-tidy warning limits by 8.

note: #3985 (misc-use-internal-linkage) is also open against the same workflow file. whichever merges second will need a trivial rebase of the warning_limit numbers.

keeping as draft until clang-tidy CI confirms the new limits.

## Changes

* Fix clang-tidy `cppcoreguidelines-narrowing-conversions` warnings in tests.

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: sdk/test/metrics/aggregation_test.cc [hunk 1]
```diff
@@ -416,8 +416,8 @@ TEST(Aggregation, Base2ExponentialHistogramAggregationMerge)
     const int expected_scale =
         aggr_point.scale_ < default_point.scale_ ? aggr_point.scale_ : default_point.scale_;
     const int expected_max_buckets = aggr_point.max_buckets_ < default_point.max_buckets_
```
Comment (dbarker) [inline sdk/test/metrics/aggregation_test.cc]: nit -  better to fix the type of the test variables to match those compared

File: sdk/test/metrics/aggregation_test.cc [hunk 2]
```diff
@@ -438,8 +438,8 @@ TEST(Aggregation, Base2ExponentialHistogramAggregationMerge)
     const int expected_scale =
         aggr_point.scale_ < zero_point.scale_ ? aggr_point.scale_ : zero_point.scale_;
     const int expected_max_buckets = aggr_point.max_buckets_ < zero_point.max_buckets_
```
Comment (dbarker) [inline sdk/test/metrics/aggregation_test.cc]: Same as above. `expected_max_buckets` can be `size_t`.

**Review by dbarker — APPROVED** [review]
Thanks for the cleanup! Just some minor optional nitpicks

File: sdk/test/metrics/aggregation_test.cc (hunk 1 above)
Comment (mateenali66) [reply sdk/test/metrics/aggregation_test.cc]: addressed in the latest commit. changed expected_max_buckets to size_t and updated the test_merge lambda parameter to match, so no cast needed.

File: exporters/otlp/test/otlp_metrics_serialization_test.cc [hunk 3]
```diff
@@ -308,7 +308,7 @@ TEST(OtlpMetricSerializationTest, Histogram)
             proto::metrics::v1::AggregationTemporality::AGGREGATION_TEMPORALITY_CUMULATIVE);
   for (size_t i = 0; i < 1; i++)
   {
-    const auto &proto_number_point = histogram.data_points(i);
+    const auto &proto_number_point = histogram.data_points(static_cast<int>(i));
```
Comment (marcalff) [inline exporters/otlp/test/otlp_metrics_serialization_test.cc]: Instead of casting `i` to an int, change this variable from size_t to int.

Now, looking at this test, I think there is something else that needs to be fixed:

- testing `i == 0 ? 100.2 : 200.2` imply the loop is executed twice, for i = 0 and i = 1.
- `for (size_t i = 0; i < 1; i++)` will only loop once, for i = 0

This is most likely an oversight from day one, when this test was written.

Please fix all similar loops to run twice (`for (int i = 0; i < 2; i++)`) to match how the test data is populated, and see if the tests all run as expected.

Tested locally on my side, and tests passed.

**Review by marcalff — CHANGES_REQUESTED** [review]
LGTM, see additional fixes in otlp_metrics_serialization.cc

File: exporters/otlp/test/otlp_metrics_serialization_test.cc (hunk 3 above)
Comment (mateenali66) [reply exporters/otlp/test/otlp_metrics_serialization_test.cc]: fixed in d2d507b. switched all three loops (Counter, Histogram, ObservableGauge) to `for (int i = 0; i < 2; i++)` and dropped the now-unnecessary `static_cast<int>(i)` at the `data_points(i)` call sites, since `i` is already the right type.

trusting your local run for the runtime verification. cmake isn't on this machine so i couldn't build the test binary myself, but the diff is mechanical: index type swap + bound change + cast removal, nothing touches the assertion logic.

Comment (marcalff) [reply exporters/otlp/test/otlp_metrics_serialization_test.cc]: Thanks.

Waiting on CI to complete, then will merge.

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix
