### PR TITLE
fix metrics race condition

### LINKED ISSUE #1542: race condition in attributes_hashmap_benchmark
We have a race condition in [`attributes_hashmap_benchmark`](https://github.com/open-telemetry/opentelemetry-cpp/runs/7657257924?check_suite_focus=true#step:5:592):

```
WARNING: ThreadSanitizer: data race (pid=12)
  Write of size 8 at 0x7ffd627125c0 by main thread:
    #0 (anonymous namespace)::BM_AttributseHashMap(benchmark::State&) <null> (attributes_hashmap_benchmark_smoketest+0x9b0d9)
    #1 benchmark::internal::FunctionBenchmark::Run(benchmark::State&) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xa7c52)
    #2 benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*, benchmark::internal::PerfCountersMeasurement*) const <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xa3a3a)
    #3 benchmark::internal::(anonymous namespace)::RunInThread(benchmark::internal::BenchmarkInstance const*, unsigned long, int, benchmark::internal::ThreadManager*, benchmark::internal::PerfCountersMeasurement*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xba4bb)
    #4 benchmark::internal::BenchmarkRunner::DoNIterations() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xbb225)
    #5 benchmark::internal::BenchmarkRunner::DoOneRepetition() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xbbd04)
    #6 benchmark::internal::(anonymous namespace)::RunBenchmarks(std::vector<benchmark::internal::BenchmarkInstance, std::allocator<benchmark::internal::BenchmarkInstance> > const&, benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x87539)
    #7 benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x8818b)
    #8 benchmark::RunSpecifiedBenchmarks() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x87c1d)
    #9 main <null> (attributes_hashmap_benchmark_smoketest+0x9b300)

  Previous read of size 8 at 0x7ffd627125c0 by thread T1:
    #0 (anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}::operator()() const <null> (attributes_hashmap_benchmark_smoketest+0x9aaa7)
    #1 void std::__invoke_impl<void, (anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}>(std::__invoke_other, (anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}&&) <null> (attributes_hashmap_benchmark_smoketest+0x9bf4e)
    #2 std::__invoke_result<(anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}>::type std::__invoke<(anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}>(std::__invoke_result&&, ((anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}&&)...) <null> (attributes_hashmap_benchmark_smoketest+0x9beb5)
    #3 void std::thread::_Invoker<std::tuple<(anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) <null> (attributes_hashmap_benchmark_smoketest+0x9be14)
    #4 std::thread::_Invoker<std::tuple<(anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}> >::operator()() <null> (attributes_hashmap_benchmark_smoketest+0x9bdba)
    #5 std::thread::_State_impl<std::thread::_Invoker<std::tuple<(anonymous namespace)::BM_AttributseHashMap(benchmark::State&)::{lambda()#2}> > >::_M_run() <null> (attributes_hashmap_benchmark_smoketest+0x9bd70)
    #6 <null> <null> (libstdc++.so.6+0xd6de3)

  Location is stack of main thread.

  Location is global '<null>' at 0x000000000000 ([stack]+0x00000001b5c0)

  Thread T1 (tid=19, finished) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:962 (libtsan.so.0+0x5ea79)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) <null> (libstdc++.so.6+0xd70a8)
    #2 (anonymous namespace)::BM_AttributseHashMap(benchmark::State&) <null> (attributes_hashmap_benchmark_smoketest+0x9b088)
    #3 benchmark::internal::FunctionBenchmark::Run(benchmark::State&) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xa7c52)
    #4 benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*, benchmark::internal::PerfCountersMeasurement*) const <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xa3a3a)
    #5 benchmark::internal::(anonymous namespace)::RunInThread(benchmark::internal::BenchmarkInstance const*, unsigned long, int, benchmark::internal::ThreadManager*, benchmark::internal::PerfCountersMeasurement*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xba4bb)
    #6 benchmark::internal::BenchmarkRunner::DoNIterations() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xbb225)
    #7 benchmark::internal::BenchmarkRunner::DoOneRepetition() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0xbbd04)
    #8 benchmark::internal::(anonymous namespace)::RunBenchmarks(std::vector<benchmark::internal::BenchmarkInstance, std::allocator<benchmark::internal::BenchmarkInstance> > const&, benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x87539)
    #9 benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x8818b)
    #10 benchmark::RunSpecifiedBenchmarks() <null> (libexternal_Scom_Ugithub_Ugoogle_Ubenchmark_Slibbenchmark.so+0x87c1d)
    #11 main <null> (attributes_hashmap_benchmark_smoketest+0x9b300)

SUMMARY: ThreadSanitizer: data race (/home/runner/.cache/bazel/e6b8d6759295e14b76bc8cb98b604748/execroot/io_opentelemetry_cpp/bazel-out/k8-tsan-fastbuild/bin/sdk/test/metrics/attributes_hashmap_benchmark_smoketest+0x9b0d9) in (anonymous namespace)::BM_AttributseHashMap(benchmark::State&)
==================
```

`hash_map.GetOrSetDefault` returns a pointer to an `Aggregation` (`DropAggregation`), for this type it should be ok as we have no read/write. But for some other type, the reads are not protected see for example:
<del>
`std::unique_ptr<Aggregation> LongSumAggregation::Merge`
</del>
`std::unique_ptr<Aggregation> LongSumAggregation::ToPoint`
We need to review reads/writes for all the aggregations.

### PR DESCRIPTION
**Pull request by esigo**
Fixes #1542 (issue)

## Changes

protects reads in aggregations.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: sdk/src/metrics/aggregation/histogram_aggregation.cc [hunk 1]
```diff
@@ -176,6 +177,7 @@ std::unique_ptr<Aggregation> DoubleHistogramAggregation::Diff(
 
 PointType DoubleHistogramAggregation::ToPoint() const noexcept
 {
+  const std::lock_guard<opentelemetry::common::SpinLockMutex> locked(lock_);
```
Comment (ThomsonTan) [inline sdk/src/metrics/aggregation/histogram_aggregation.cc:180]: Wondering what kind of race conditino is this mutex protecting?

Comment (esigo) [reply sdk/src/metrics/aggregation/histogram_aggregation.cc:180]: both reads and writes should be protected. It can happen that while we are reading, some other thread writes to this filed.

**Review by lalitb — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]
