### PR TITLE
Fix missing notify of conditional variable in OTLP HTTP exporter test

### LINKED ISSUE #857: Conditional variable cv_got_events in otlp_http_exporter_test is never notified
**Describe your environment**
otlp_http_exporter_test use [conditional variable](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/test/otlp_http_exporter_test.cc#L45) to sync between main thread and HTTP response handling thread, but the conditional variable is never notified even when the HTTP response is completed processing.

**Steps to reproduce**
Run `exporter.otlp.OtlpHttpExporterTestPeer.ExportJsonIntegrationTest`.

**What is the expected behavior?**
The test should pass shortly.

**What is the actual behavior?**
The test passed, but it also causes timeout.

**Additional context**

### PR DESCRIPTION
**Pull request by ThomsonTan**
Fixes #857 

## Changes

Added `notify_one` call to `cv_got_events` right after HTTP response processing.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: exporters/otlp/test/otlp_http_exporter_test.cc [hunk 1]
```diff
@@ -124,18 +126,22 @@ class OtlpHttpExporterTestPeer : public ::testing::Test, public HTTP_SERVER_NS::
...
     else
     {
       std::unique_lock<std::mutex> lk(mtx_requests);
       response.headers["Content-Type"] = "text/plain";
       response.body                    = "404 Not Found";
-      return 200;
+      response_status = 200;
     }
+
+    cv_got_events.notify_one();
```
Comment (lalitb) [inline exporters/otlp/test/otlp_http_exporter_test.cc:142]: why is this needed ? `cv.wait_for` was supposed to be unblocked with a timeout. I think this will fail now if the test is modified so that `cv.wait_for` has multiple requests to wait for, as now it will be unblocked after a single request?

Comment (ThomsonTan) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: Timeout in `cv.wait_for` is the last resort. `cv` should be waked up anytime its checking condition could be changed, so its condition could be re-checked instead of waiting for timing out. `notify_one` just tell `cv` to recheck so it should not trigger failure behavior?

cc @owent

Comment (lalitb) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: Does it mean that without notification, the `cv` will keep blocked for 2sec (as configured) even though the condition is satisfied early?

Comment (ThomsonTan) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: Yes, this is the case the PR trying to fix.

Comment (lalitb) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: Asking because we are using this construct in other places too (https://github.com/open-telemetry/opentelemetry-cpp/blob/7fca2c39586696d71de4f1feeb9ee6705a4e0261/ext/test/http/curl_http_test.cc#L124), probably they need a change too ( in separate PR ).

**Review by lalitb — APPROVED** [review]

File: exporters/otlp/test/otlp_http_exporter_test.cc (hunk 1 above)
Comment (ThomsonTan) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: You are right, it is needed in curl_http_test.cc as well. Added the change to the PR and avoid another 2 timeout to happen there. Thanks for the catch.

Comment (owent) [reply exporters/otlp/test/otlp_http_exporter_test.cc:142]: > Timeout in `cv.wait_for` is the last resort. `cv` should be waked up anytime its checking condition could be changed, so its condition could be re-checked instead of waiting for timing out. `notify_one` just tell `cv` to recheck so it should not trigger failure behavior?
> 
> cc @owent

You are right. LGTM.

**Comment by owent** [comment]
Could you please remove the `TODO` I omit in #853 ? I think there is no need to create a PR just to remove the `TODO` comment.

**Comment by ThomsonTan** [comment]
> Could you please remove the `TODO` I omit in #853 ? I think there is no need to create a PR just to remove the `TODO` comment.

Sure, just removed that.
