### PR TITLE
Waiting a longer time when run unit tests of http client, which may take a long time when run under valgrind.

### LINKED ISSUE #1049: Unit test failing in CI: OtlpHttpExporterTestPeer.ExportJsonIntegrationTest
One of the failure instances:
https://github.com/open-telemetry/opentelemetry-cpp/runs/4083453037?check_suite_focus=true

```
[ RUN      ] OtlpHttpExporterTestPeer.ExportJsonIntegrationTest
exporters/otlp/test/otlp_http_exporter_test.cc:240: Failure
Value of: waitForRequests(2, old_count + 1)
  Actual: false
Expected: true
[  FAILED  ] OtlpHttpExporterTestPeer.ExportJsonIntegrationTest (4446 ms)
```

### PR DESCRIPTION
**Pull request by owent**
Signed-off-by: owentou <owentou@tencent.com>

Fixes #1049

## Changes

Increase timeout for http client. We find 8s is not enough sometime.

> https://github.com/open-telemetry/opentelemetry-cpp/runs/4793495501

For significant contributions please make sure you have completed the following items:

* [x] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: exporters/otlp/test/otlp_http_log_exporter_test.cc [hunk 1]
```diff
@@ -251,7 +251,7 @@ TEST_F(OtlpHttpLogExporterTestPeer, ExportJsonIntegrationTest)
     report_span_id.assign(span_id_hex, sizeof(span_id_hex));
   }
 
-  ASSERT_TRUE(waitForRequests(8, old_count + 1));
+  ASSERT_TRUE(waitForRequests(30, old_count + 1));
```
Comment (lalitb) [inline exporters/otlp/test/otlp_http_log_exporter_test.cc:254]: interesting. We started with 2, then 8, and now 30. Didn't know it's that slow with Valgrind :)

Comment (owent) [reply exporters/otlp/test/otlp_http_log_exporter_test.cc:254]: I found otlp http client test under valgrind takes 6s most of the time. The `//sdk/test/_metrics:metric_instrument_test` take the longest time(almost 1minute). But sometime it takes more time to finish, maybe the CI node is busy at that time?

Comment (lalitb) [reply exporters/otlp/test/otlp_http_log_exporter_test.cc:254]: Why do we need to increase the HTTP wait time if it's 6 secs most of the time as part of this PR? We should eventually remove the old metrics tests once new implementation is ready.

Comment (esigo) [reply exporters/otlp/test/otlp_http_log_exporter_test.cc:254]: This failure is happening every now and then in my PR [recently](https://github.com/open-telemetry/opentelemetry-cpp/runs/4827044509?check_suite_focus=true#step:5:134).

**Review by esigo — APPROVED** [review]
LGTM

File: exporters/otlp/test/otlp_http_log_exporter_test.cc (hunk 1 above)
Comment (lalitb) [reply exporters/otlp/test/otlp_http_log_exporter_test.cc:254]: We can merge this PR if that's the case. If the problem persists, we can think of mocking the HTTP responses instead of using a real server.

**Comment by lalitb** [comment]
@owent  - can you please rebase this PR with main, to allow merging.

**Comment by owent** [comment]
> @owent - can you please rebase this PR with main, to allow merging.

Done

File: exporters/otlp/test/otlp_http_log_exporter_test.cc (hunk 1 above)
Comment (owent) [reply exporters/otlp/test/otlp_http_log_exporter_test.cc:255]: Agree
