### PR TITLE
[EXPORTER] ostream log exporter, fix memory ownership issues

### LINKED ISSUE #2651: common::MakeAttributes creates garbled output for std::string
**Describe your environment**
OS: Debian bookworm
GCC: 12.2.0
Version: 054b0dc2 ([RELEASE] Release opentelemetry-cpp version 1.15.0 (#2639), 2024-04-21), also present in 1.11.0.

**Steps to reproduce**
- Download patch to ostream test [0001-Show-error-with-garbled-output.zip](https://github.com/open-telemetry/opentelemetry-cpp/files/15151907/0001-Show-error-with-garbled-output.zip)
- unzip 0001-Show-error-with-garbled-output.patch.zip
- git am 0001-Show-error-with-garbled-output.patch
- cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=ON -DWITH_OTLP_GRPC=ON -DWITH_OTLP_HTTP=ON -DWITH_ABSEIL=ON -DWITH_BENCHMARK=OFF -DCMAKE_CXX_STANDARD=17
- cmake --build build --target ostream_log_test && ctest --test-dir build -R IntegrationTestWithEventId --verbose

Outputs:

```
...
539: {
539:   timestamp          : 0
539:   observed_timestamp : 1714407256398793342
539:   severity_num       : 5
539:   severity_text      : DEBUG
539:   body               : Hello {key1} {key2}
539:   resource           : 
539:     service.name: unknown_service
539:     telemetry.sdk.version: 1.15.0
539:     telemetry.sdk.name: opentelemetry
539:     telemetry.sdk.language: cpp
539:   attributes         : 
539:     key2: �fA�U
539: 
539: ��A����abcd
539:     key1: 123
539:   event_id           : 12345678
539:   event_name         : test_event_id
539:   trace_id           : 00000000000000000000000000000000
539:   span_id            : 0000000000000000
539:   trace_flags        : 00
539:   scope              : 
539:     name             : opentelelemtry_library
539:     version          : 1.15.0
539:     schema_url       : https://opentelemetry.io/schemas/1.11.0
539:     attributes       : 
539:       scope.attr.key: 123
539: }
...
```

If I use the `SimpleLogRecordProcessor` there is no garbled output. And if I pass in a `const char*` via `someString.c_str()` and use the batched processor I also get garbled output.

**What is the expected behavior?**
That the strings I sent are outputted properly.

**What is the actual behavior?**
Garbled output.

**Additional context**

I would also be interested to know if the bug is limited to the ostream exporter or also applies to other exporters, we want tot use otlp with grpc and http in production.

This looks like a lifetime issue with regarding common::AttributeValue.

### LINKED ISSUE #3135: heap-use-after-free with BatchLogRecordProcessor
**Describe your environment**
OpenTelemetry v1.17.0

**Steps to reproduce**
Sample code: https://github.com/sjinks/otel-heap-use-after-free
Sample run: https://github.com/sjinks/otel-heap-use-after-free/actions/runs/11758831588/job/32757617053

**What is the expected behavior?**
There should be no errors.

**What is the actual behavior?**
The application crashed because of the heap-use-after-free-error

```
=5853==ERROR: AddressSanitizer: heap-use-after-free on address 0x6030000005c8 at pc 0x55707b183c86 bp 0x7f82e12fe770 sp 0x7f82e12fdf38
READ of size 6 at 0x6030000005c8 thread T1
    #0 0x55707b183c85 in __interceptor_strlen (/home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/build/bug-repro+0x46c85) (BuildId: 3dbd37ecfe9134972fe6a448909a1b651fdd1e62)
    #1 0x7f82e3b3ceac in std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x13ceac) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
    #2 0x55707b247a33 in void opentelemetry::v1::exporter::ostream_common::print_value<char const*>(char const* const&, std::ostream&) /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/exporters/ostream/include/opentelemetry/exporters/ostream/common_utils.h:25:8
    #3 0x55707b2435cb in auto opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&)::'lambda'(auto&&)::operator()<char const* const&>(auto&&) const /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.
    #4 0x55707b24ab4d in auto std::__invoke_impl<void, opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&)::'lambda'(auto&&), char const* const&>(std::__invoke_other, opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, doub
    #5 0x55707b248277 in std::__invoke_result<auto, char const* const&>::type std::__invoke<opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&)::'lambda'(auto&&), char const* const&>(auto&&, char const* const&) /usr/include/c++/11/bits/invoke.h:96:40
    #6 0x55707b243a33 in std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&)::'lambda'(auto&&)&&, std::variant<bool, int, long, uns
    #7 0x55707b243f3a in decltype(auto) std::__do_visit<std::__detail::__variant::__deduce_visit_result<void>, opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&)::'lambda'(auto&&), std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd:
    #8 0x55707b243fa1 in std::invoke_result<auto, std::conditional<is_lvalue_reference_v<std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&>, std::variant_alternative<0ul, std::remove_reference<decltype(__as(declval<std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd
    #9 0x55707b23f9a8 in opentelemetry::v1::exporter::ostream_common::print_value(std::variant<bool, int, long, unsigned int, double, char const*, opentelemetry::v1::nostd::string_view, opentelemetry::v1::nostd::span<bool const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned int const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<double const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<opentelemetry::v1::nostd::string_view const, 18446744073709551615ul>, unsigned long, opentelemetry::v1::nostd::span<unsigned long const, 18446744073709551615ul>, opentelemetry::v1::nostd::span<unsigned char const, 18446744073709551615ul> > const&, std::ostream&) /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/exporters/ostream/include/opentelemetry/exporters/ostream/commo
    #10 0x55707b23e5a4 in opentelemetry::v1::exporter::logs::OStreamLogRecordExporter::Export(opentelemetry::v1::nostd::span<std::unique_ptr<opentelemetry::v1::sdk::logs::Recordable, std::default_delete<opentelemetry::v1::sdk::logs::Recordable> >, 18446744073709551615ul> const&) /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/exporters/ostream/src/log_record_exporter.cc:111:57
    #11 0x55707b276fe7 in opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::Export() /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/sdk/src/logs/batch_log_record_processor.cc:223:22
    #12 0x55707b276cc6 in opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::DoBackgroundWork() /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/sdk/src/logs/batch_log_record_processor.cc:178:11
    #13 0x55707b27c429 in void std::__invoke_impl<void, void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*>(std::__invoke_memfun_deref, void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*&&)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*&&) /usr/include/c++/11/bits/invoke.h:74:46
    #14 0x55707b27c37c in std::__invoke_result<void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*>::type std::__invoke<void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*>(void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*&&)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*&&) /usr/include/c++/11/bits/invoke.h:96:40
    #15 0x55707b27c2dc in void std::thread::_Invoker<std::tuple<void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/11/bits/std_thread.h:259:26
    #16 0x55707b27c22b in std::thread::_Invoker<std::tuple<void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*> >::operator()() /usr/include/c++/11/bits/std_thread.h:266:20
    #17 0x55707b27c1c3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::*)(), opentelemetry::v1::sdk::logs::BatchLogRecordProcessor*> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211:20
    #18 0x7f82e3adc252  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc252) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
    #19 0x7f82e3694ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
    #20 0x7f82e372684f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
0x6030000005c8 is located 24 bytes inside of 30-byte region [0x6030000005b0,0x6030000005ce)
freed by thread T0 here:
    #0 0x55707b22bfbd in operator delete(void*) (/home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/build/bug-repro+0xeefbd) (BuildId: 3dbd37ecfe9134972fe6a448909a1b651fdd1e62)
    #1 0x7f82e3ac46f2 in std::runtime_error::~runtime_error() (/lib/x86_64-linux-gnu/libstdc++.so.6+0xc46f2) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
    #2 0x7f82e3629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
previously allocated by thread T0 here:
    #0 0x55707b22b75d in operator new(unsigned long) (/home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/build/bug-repro+0xee75d) (BuildId: 3dbd37ecfe9134972fe6a448909a1b651fdd1e62)
    #1 0x7f82e3af4978 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xf4978) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
Thread T1 created by T0 here:
    #0 0x55707b1d9e0c in __interceptor_pthread_create (/home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/build/bug-repro+0x9ce0c) (BuildId: 3dbd37ecfe9134972fe6a448909a1b651fdd1e62)
    #1 0x7f82e3adc328 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc328) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
    #2 0x55707b2764d0 in opentelemetry::v1::sdk::logs::BatchLogRecordProcessor::BatchLogRecordProcessor(std::unique_ptr<opentelemetry::v1::sdk::logs::LogRecordExporter, std::default_delete<opentelemetry::v1::sdk::logs::LogRecordExporter> >&&, opentelemetry::v1::sdk::logs::BatchLogRecordProcessorOptions const&) /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/sdk/src/logs/batch_log_record_processor.cc:58:7
    #3 0x55707b26c501 in opentelemetry::v1::sdk::logs::BatchLogRecordProcessorFactory::Create(std::unique_ptr<opentelemetry::v1::sdk::logs::LogRecordExporter, std::default_delete<opentelemetry::v1::sdk::logs::LogRecordExporter> >&&, opentelemetry::v1::sdk::logs::BatchLogRecordProcessorOptions const&) /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/vcpkg/buildtrees/opentelemetry-cpp/src/v1.17.0-b9ea5cab17.clean/sdk/src/logs/batch_log_record_processor_factory.cc:25:63
    #4 0x55707b22e18b in main /home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/repro.cpp:19:22
    #5 0x7f82e3629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
SUMMARY: AddressSanitizer: heap-use-after-free (/home/runner/work/otel-heap-use-after-free/otel-heap-use-after-free/build/bug-repro+0x46c85) (BuildId: 3dbd37ecfe9134972fe6a448909a1b651fdd1e62) in __interceptor_strlen
Shadow bytes around the buggy address:
  0x0c067fff8060: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c067fff8070: fd fa fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c067fff8080: fd fd fd fa fa fa 00 00 06 fa fa fa 00 00 03 fa
  0x0c067fff8090: fa fa 00 00 07 fa fa fa 00 00 00 00 fa fa 00 00
  0x0c067fff80a0: 00 fa fa fa 00 00 00 fa fa fa fd fd fd fa fa fa
=>0x0c067fff80b0: fd fd fd fa fa fa fd fd fd[fd]fa fa 00 00 00 fa
  0x0c067fff80c0: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c067fff80d0: fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5853==ABORTING
```

**Additional context**
```cpp
    opentelemetry::sdk::logs::BatchLogRecordProcessorOptions options{2048, std::chrono::milliseconds(5000), 512};
    auto processor = opentelemetry::sdk::logs::BatchLogRecordProcessorFactory::Create(std::move(exporter), options);

//...

    try {
        throw std::runtime_error("error");
    }
    catch (const std::exception &e) {
        auto logger = opentelemetry::logs::Provider::GetLoggerProvider()->GetLogger("example");
        logger->Error(e.what());
    }
```

The bug happens when the `catch` block is left before the `BatchLogRecordProcessor` processes the data.

My understanding is that the log message is stored `ReadWriteLogRecord::body_` which is `opentelemetry::common::AttributeValue`, a `nostd::variant` holding a `const char*` value. When `e` goes out of the scope and gets destructed, the memory pointed to by `e.what()` is also freed. However, because `AttributeValue` does not own the data, it is left with a dangling pointer.

The fix will probably be to replace `AttributeValue` with `OwnedAttributeValue` (this will affect `body_` and `attributes_map_`).

Refs:
* https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.17.0/sdk/include/opentelemetry/sdk/logs/read_write_log_record.h#L191
* https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.17.0/sdk/include/opentelemetry/sdk/logs/read_write_log_record.h#L190

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #3135
Fixes #2651

## Changes

Fixed the following memory ownership issues in the ostream log exporter:

* In class `ReadWriteLogRecord`, member `body_` now owns a copy of the log body
* In class `ReadWriteLogRecord`, member `attributes_map_` now owns a copy of log attributes

This prevents the use of stale pointers, that could lead to crashes previously.

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: sdk/src/logs/read_write_log_record.cc [hunk 1]
```diff
@@ -30,7 +31,7 @@ ReadWriteLogRecord::ReadWriteLogRecord()
     : severity_(opentelemetry::logs::Severity::kInvalid),
       resource_(nullptr),
       instrumentation_scope_(nullptr),
-      body_(nostd::string_view()),
+      body_(std::string()),
```
Comment (dbarker) [inline sdk/src/logs/read_write_log_record.cc:34]: Should we not initialize the body since it is an "any" type and optional?

Comment (dbarker) [reply sdk/src/logs/read_write_log_record.cc:34]: Looks like we will have to initialize the variant to some value (no std::monostate like type available to signal empty). Perhaps an empty string is okay.

**Review by lalitb — APPROVED** [review]
Nicely done, thanks. I would ideally prefer to get rid of `ReadableLogRecord`, and just have `ReadWriteLogRecord` (probably renamed to `LogData`), and so have the API consistent with `SpanData`, but that's not related to the issue :)

**Comment by ThomsonTan** [comment]
Is this a breaking change if `ReadWriteLogRecord` is used by the user? Mention this in the changelog if so.

**Comment by ThomsonTan** [comment]
> Nicely done, thanks. I would ideally prefer to get rid of `ReadableLogRecord`, and just have `ReadWriteLogRecord` (probably renamed to `LogData`), and so have the API consistent with `SpanData`, but that's not related to the issue :)

Seems https://github.com/open-telemetry/opentelemetry-cpp/pull/3147 includes the renaming to `LogRecordData`.

**Comment by marcalff** [comment]
Added an important changes section in the CHANGELOG, to address @ThomsonTan comments.

Waiting for @owent approval, as an alternative fix to PR #3147.

**Comment by marcalff** [comment]
Additional testing:

* Manually ported the test case patch from #2651 to a plain (unchanged) main repo, executed the tests, inspected the output: issue reproduced using the main branch
* Manually ported the same with this fix, executed the tests, inspected the output: issue is fixed.

**Comment by owent** [comment]
> Added an important changes section in the CHANGELOG, to address @ThomsonTan comments.
> 
> Waiting for @owent approval, as an alternative fix to PR #3147.

This changes API, and may make users can not compile. I prefer to use #3147, which only change the APIs in v2 version.

**Comment by lalitb** [comment]
> This changes API, and may make users can not compile. Personally, I prefer to use https://github.com/open-telemetry/opentelemetry-cpp/pull/3147, which only change the APIs in v2 version.

@owent - this is only SDK breaking change, so do we still need to have v2 ?

**Comment by marcalff** [comment]
> > This changes API, and may make users can not compile. Personally, I prefer to use #3147, which only change the APIs in v2 version.
> 
> @owent - this is only SDK breaking change, so do we still need to have v2 ?

See related discussion https://github.com/open-telemetry/opentelemetry-cpp/pull/3147#discussion_r2095741789

File: sdk/src/logs/read_write_log_record.cc (hunk 1 above)
Comment (marcalff) [reply sdk/src/logs/read_write_log_record.cc:34]: Initializing body to an empty string by default, which is the same as previous behavior.

**Comment by owent** [comment]
> > This changes API, and may make users can not compile. Personally, I prefer to use #3147, which only change the APIs in v2 version.
> 
> @owent - this is only SDK breaking change, so do we still need to have v2 ?

Sorry, I shouldn't use the ABI version macro. My goal is to allow users time to migrate their code when upgrading otel-cpp, rather than causing immediate compilation errors.

**Comment by lalitb** [comment]
> Sorry, I shouldn't use the ABI version macro. My goal is to allow users time to migrate their code when upgrading otel-cpp, rather than causing immediate compilation errors.

Thanks for clarifying. As I understand it, compile-time errors would only occur in the following cases:
- Custom exporters using ReadWriteLogRecord or ReadableLogRecord.
- Custom processors that rely on ReadWriteLogRecord or ReadableLogRecord for record filtering or redaction.

Given that this is likely a small subset of users, I think introducing these breaking changes should be fine.

**Comment by owent** [comment]
> > Sorry, I shouldn't use the ABI version macro. My goal is to allow users time to migrate their code when upgrading otel-cpp, rather than causing immediate compilation errors.
> 
> Thanks for clarifying. As I understand it, compile-time errors would only occur in the following cases:
> 
> * Custom exporters using ReadWriteLogRecord or ReadableLogRecord.
> * Custom processors that rely on ReadWriteLogRecord or ReadableLogRecord for record filtering or redaction.
> 
> None of the core processors and exporters are affected by this change. Given that this is likely a small subset of users, I think introducing these breaking changes should be fine. The changelog should clearly specify the migration steps for affected users in this scenario.

Yes, but in #3147 , a new record class `LogRecordData` is added, which is used by ostream exporter. This class is added only to make the similar name as `trace::SpanData`. But it's almost the same as `ReadWriteLogRecord`, the changes of `ReadWriteLogRecord` just want to keed ABI compatibility to resolve the comment in <https://github.com/open-telemetry/opentelemetry-cpp/pull/3147#issuecomment-2480527602> .

**Comment by marcalff** [comment]
> > > Sorry, I shouldn't use the ABI version macro. My goal is to allow users time to migrate their code when upgrading otel-cpp, rather than causing immediate compilation errors.
> > 
> > 
> > Thanks for clarifying. As I understand it, compile-time errors would only occur in the following cases:
> > 
> > * Custom exporters using ReadWriteLogRecord or ReadableLogRecord.
> > * Custom processors that rely on ReadWriteLogRecord or ReadableLogRecord for record filtering or redaction.
> > 
> > None of the core processors and exporters are affected by this change. Given that this is likely a small subset of users, I think introducing these breaking changes should be fine. The changelog should clearly specify the migration steps for affected users in this scenario.
> 

The changelog already gives details about this, in the important changes section.

I agree that the potential build break will affect only a small subset of users, which is why this should be fine.

Also, note that people affected by the build break will be users who deliberately reuse some SDK classes in their own implementation: they should be fully aware of risks when choosing to do so.

> Yes, but in #3147 , a new record class `LogRecordData` is added, which is used by ostream exporter. This class is added only to make the similar name as `trace::SpanData`. But it's almost the same as `ReadWriteLogRecord`, the changes of `ReadWriteLogRecord` just want to keed ABI compatibility to resolve the comment in [#3147 (comment)](https://github.com/open-telemetry/opentelemetry-cpp/pull/3147#issuecomment-2480527602) .

The comment about ABI changes in the SDK is technically correct, as `ReadWriteLogRecord` indeed changed (in the initial fix from #3147).

However, I think this comment should not be blocking: opentelemetry-cpp does not guarantee binary stability for the SDK implementation, so if an SDK class changes, it changes.

The rationale for creating yet another class like LogRecordData is to preserve a binary compatible `ReadWriteLogRecord`,
but if there is no need to preserve binary compatibility (there is none), everything can be greatly simplified.

This entire fix (the present PR) is +70 -57 lines, and this includes the documentation in the changelog, and unit tests adjustments.

Please, let's not blow the fix scope out of proportions, when it can be done simply.

**Comment by owent** [comment]
> > > > Sorry, I shouldn't use the ABI version macro. My goal is to allow users time to migrate their code when upgrading otel-cpp, rather than causing immediate compilation errors.
> > > 
> > > 
> > > Thanks for clarifying. As I understand it, compile-time errors would only occur in the following cases:
> > > 
> > > * Custom exporters using ReadWriteLogRecord or ReadableLogRecord.
> > > * Custom processors that rely on ReadWriteLogRecord or ReadableLogRecord for record filtering or redaction.
> > > 
> > > None of the core processors and exporters are affected by this change. Given that this is likely a small subset of users, I think introducing these breaking changes should be fine. The changelog should clearly specify the migration steps for affected users in this scenario.
> 
> The changelog already gives details about this, in the important changes section.
> 
> I agree that the potential build break will affect only a small subset of users, which is why this should be fine.
> 
> Also, note that people affected by the build break will be users who deliberately reuse some SDK classes in their own implementation: they should be fully aware of risks when choosing to do so.
> 
> > Yes, but in #3147 , a new record class `LogRecordData` is added, which is used by ostream exporter. This class is added only to make the similar name as `trace::SpanData`. But it's almost the same as `ReadWriteLogRecord`, the changes of `ReadWriteLogRecord` just want to keed ABI compatibility to resolve the comment in [#3147 (comment)](https://github.com/open-telemetry/opentelemetry-cpp/pull/3147#issuecomment-2480527602) .
> 
> The comment about ABI changes in the SDK is technically correct, as `ReadWriteLogRecord` indeed changed (in the initial fix from #3147).
> 
> However, I think this comment should not be blocking: opentelemetry-cpp does not guarantee binary stability for the SDK implementation, so if an SDK class changes, it changes.
> 
> The rationale for creating yet another class like LogRecordData is to preserve a binary compatible `ReadWriteLogRecord`, but if there is no need to preserve binary compatibility (there is none), everything can be greatly simplified.
> 
> This entire fix (the present PR) is +70 -57 lines, and this includes the documentation in the changelog, and unit tests adjustments.
> 
> Please, let's not blow the fix scope out of proportions, when it can be done simply.

OK, I closed #3147, let's use this PR.

**Review by owent — APPROVED** [review]
