### PR TITLE
Fix session lock of `OtlpHttpClient`

### LINKED ISSUE #1759: May crash when using OTLP Http exporter in async mode
**Describe your environment** 

OS: Linux
Compiler: GCC 8

**Additional context**

We should also lock `session_manager_lock_` when create and add new session into `OtlpHttpClient`.

```bash
#3  std::unordered_map<opentelemetry_ecosystem::v1::ext::http::client::Session const*, opentelemetry_ecosystem::v1::exporter::otlp::OtlpHttpClient::HttpSessionData, std::hash<opentelemetry_ecosystem::v1::ext::http::client::Session const*>, std::equal_to<opentelemetry_ecosystem::v1::ext::http::client::Session const*>, std::allocator<std::pair<opentelemetry_ecosystem::v1::ext::http::client::Session const* const, opentelemetry_ecosystem::v1::exporter::otlp::OtlpHttpClient::HttpSessionData> > >::find (__x=<optimized out>, this=0x7fe009315930)
    at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/unordered_map.h:921
#4  opentelemetry_ecosystem::v1::exporter::otlp::OtlpHttpClient::ReleaseSession (this=0x7fe009315880, session=...)
    at external/opentelemetry-cpp-ecosystem/exporters/otlp/src/otlp_http_client.cc:729
#5  0x0000000000f762a5 in opentelemetry_ecosystem::v1::exporter::otlp::(anonymous namespace)::ResponseHandler::Unbind (result=opentelemetry::v1::sdk::common::ExportResult::kSuccess, 
    this=0x7fddc8e25820) at external/opentelemetry-cpp-ecosystem/exporters/otlp/src/otlp_http_client.cc:300
#6  opentelemetry_ecosystem::v1::exporter::otlp::(anonymous namespace)::ResponseHandler::OnResponse (this=0x7fddc8e25820, response=...)
    at external/opentelemetry-cpp-ecosystem/exporters/otlp/src/otlp_http_client.cc:131
#7  0x0000000000f81057 in opentelemetry_ecosystem::v1::ext::http::client::curl::Session::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&)>::operator() (
    operation=..., __closure=0x7fe0077476a0) at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/shared_ptr_base.h:1018
#8  std::_Function_handler<void (opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&), opentelemetry_ecosystem::v1::ext::http::client::curl::Session::SendRequest(std::shared_ptr<opentelemetry::v1::ext::http::client::EventHandler>)::{lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&)#1}>::_M_invoke(std::_Any_data const&, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&) () at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/std_function.h:297
#9  0x0000000000f884e6 in std::function<void (opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&)>::operator()(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation&) const (__args#0=..., this=0x7fddc8863260) at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/std_function.h:682
#10 opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation::Cleanup() () at external/opentelemetry-cpp-ecosystem/ext/src/http/client/curl/http_operation_curl.cc:300
#11 0x0000000000f88c92 in opentelemetry_ecosystem::v1::ext::http::client::curl::HttpOperation::PerformCurlMessage(CURLcode) ()
    at external/opentelemetry-cpp-ecosystem/ext/src/http/client/curl/http_operation_curl.cc:551
#12 0x0000000000f82e4c in opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)>::operator() (
    __closure=<optimized out>, self=0x7fe0092d3210) at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/unique_ptr.h:337
#13 std::__invoke_impl<void, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)>, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*> (__f=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/invoke.h:60
#14 std::__invoke<opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)>, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*> (__fn=<optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/invoke.h:95
#15 std::thread::_Invoker<std::tuple<opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)>, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*> >::_M_invoke<0, 1> (this=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/thread:244
#16 std::thread::_Invoker<std::tuple<opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::<lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)>, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*> >::operator() (this=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/thread:253
#17 std::thread::_State_impl<std::thread::_Invoker<std::tuple<opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::{lambda(opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*)#1}, opentelemetry_ecosystem::v1::ext::http::client::curl::HttpClient*> > >::_M_run() ()
    at /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/thread:196
#18 0x00007fe02eca0b73 in ?? () from /lib64/libstdc++.so.6
#19 0x00007fe02caff2de in start_thread (arg=<optimized out>) at pthread_create.c:486
---Type <return> to continue, or q <return> to quit---
#20 0x00007fe02c618e83 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by owent**
Signed-off-by: owent <admin@owent.net>

Fixes #1759 
## Changes

+ Fix session lock of `OtlpHttpClient`

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by owent** [comment]
The failed job seems not a problem of this PR.

File: exporters/otlp/src/otlp_http_client.cc [hunk 1]
```diff
@@ -981,16 +981,19 @@ void OtlpHttpClient::addSession(HttpSessionData &&session_data) noexcept
...
-  opentelemetry::ext::http::client::Session *key = session_data.session.get();
-  ResponseHandler *handle = static_cast<ResponseHandler *>(session_data.event_handle.get());
-
-  handle->Bind(this, *key);
+  std::shared_ptr<opentelemetry::ext::http::client::Session> session = session_data.session;
+  std::shared_ptr<opentelemetry::ext::http::client::EventHandler> handle =
+      session_data.event_handle;
+  {
+    std::lock_guard<std::recursive_mutex> guard{session_manager_lock_};
+    static_cast<ResponseHandler *>(handle.get())->Bind(this, *session);
```
Comment (lalitb) [inline exporters/otlp/src/otlp_http_client.cc:989]: Does this statement needs to be under lock ?

File: exporters/otlp/src/otlp_http_client.cc [hunk 2]
```diff
@@ -981,16 +981,19 @@ void OtlpHttpClient::addSession(HttpSessionData &&session_data) noexcept
...
 
-  HttpSessionData &store_session_data = running_sessions_[key];
-  store_session_data                  = std::move(session_data);
+    HttpSessionData &store_session_data = running_sessions_[session.get()];
```
Comment (lalitb) [inline exporters/otlp/src/otlp_http_client.cc:991]: Just curious , why can't we just use `session_data.session.get()` instead of `session.get()` for indexing here?

File: exporters/otlp/src/otlp_http_client.cc (hunk 1 above)
Comment (owent) [reply exporters/otlp/src/otlp_http_client.cc:989]: No, it's not necessary, but I think `ResponseHandler::Bind` and inserting element into `running_sessions_` below should work together logically.

**Review by lalitb — APPROVED** [review]
LGTM. Thanks for the fix.
