### PR TITLE
fix baggage propagation for empty/invalid baggage context

### LINKED ISSUE #1366: Empty headers injected by HTTP and Baggage propagator
If the HTTP propagator is used on an invalid context or the baggage propagator is used on an empty baggage, the resulting header map will contain empty values. I don't know if this is intended or not, but I think it'd be more user friendly if empty values wouldn't be injected, so the user wouldn't have to remove or check them manually before using them as HTTP request headers.

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1366

## Changes

If the context doesn't have baggage, or the baggage data is empty/invalid, the HTTP request headers shouldn't contain empty baggage values for baggage. 
 
For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: api/test/baggage/propagation/baggage_propagator_test.cc [hunk 1]
```diff
@@ -82,3 +82,32 @@ TEST(BaggagePropagatorTest, ExtractAndInjectBaggage)
...
+    // Test empty baggage in context
+    BaggageCarrierTest carrier1;
+    carrier1.headers_[baggage::kBaggageHeader.data()] = "";
+    context::Context ctx1                             = context::Context{};
+    context::Context ctx2                             = format.Extract(carrier1, ctx1);
+    format.Inject(carrier, ctx2);
+    EXPECT_EQ(carrier.headers_.find(baggage::kBaggageHeader), carrier.headers_.end());
+  }
+  {
+    // Invali baggage in context
```
Comment (ThomsonTan) [inline api/test/baggage/propagation/baggage_propagator_test.cc:104]:
```suggestion
    // Invalid baggage in context
```

File: api/include/opentelemetry/baggage/propagation/baggage_propagator.h [hunk 2]
```diff
@@ -21,7 +21,11 @@ class BaggagePropagator : public opentelemetry::context::propagation::TextMapPro
               const opentelemetry::context::Context &context) noexcept override
   {
     auto baggage = opentelemetry::baggage::GetBaggage(context);
-    carrier.Set(kBaggageHeader, baggage->ToHeader());
+    auto header  = baggage->ToHeader();
+    if (header.size())
```
Comment (ThomsonTan) [inline api/include/opentelemetry/baggage/propagation/baggage_propagator.h:25]: Do we need do something similar in line 36 (new file), and ignore call to `SetBaggage` if `FromHeader()` returned an empty or invalid baggage?

Comment (lalitb) [reply api/include/opentelemetry/baggage/propagation/baggage_propagator.h:25]: Yes, was thinking so, but it would need more changes in Context API - to add a copy constructor. Just tried to API changes as of now.

Comment (lalitb) [reply api/include/opentelemetry/baggage/propagation/baggage_propagator.h:25]: Ok seems the default copy constructor is usable for context::Context, have done the changes as requested.

File: api/include/opentelemetry/baggage/propagation/baggage_propagator.h [hunk 3]
```diff
@@ -21,15 +21,27 @@ class BaggagePropagator : public opentelemetry::context::propagation::TextMapPro
...
     auto baggage                   = opentelemetry::baggage::Baggage::FromHeader(baggage_str);
-    return opentelemetry::baggage::SetBaggage(context, baggage);
+
+    if (baggage->ToHeader().size())
+    {
+      return opentelemetry::baggage::SetBaggage(context, baggage);
+    }
+    else
+    {
+      return context::Context(context);
```
Comment (esigo) [inline api/include/opentelemetry/baggage/propagation/baggage_propagator.h:43]: nit:
```suggestion
      return context;
```

**Review by esigo — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]
