### PR TITLE
Fixes tsan warnings

### LINKED ISSUE #3530: [TSAN] ThreadSanitizer: data race with clang 20 and libc++
**Describe your environment**

OS: Linux
Compiler: Clang 20.1.3 with libc++

**Additional context**

```bash
[Log Debug][external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_exporter.cc:185]: [OTLP TRACE HTTP Exporter] Export 1 trace span(s) success
==================
WARNING: ThreadSanitizer: data race (pid=37518)
  Write of size 8 at 0x721400000e68 by thread T1:
    #0 __tsan_memcpy build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_memintrinsics.cpp:27:3 (example_otlp_http+0x12d42e) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #1 opentelemetry::v1::ext::http::client::curl::HttpOperation::Cleanup() /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_operation_curl.cc:417:36 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0xd310e) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #2 opentelemetry::v1::ext::http::client::curl::HttpOperation::PerformCurlMessage(CURLcode) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_operation_curl.cc:1426:5 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0xd729c) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #3 opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0::operator()(opentelemetry::v1::ext::http::client::curl::HttpClient*) const /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_client_curl.cc:520:28 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x9b3d8) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #4 decltype(std::declval<opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0>()(std::declval<opentelemetry::v1::ext::http::client::curl::HttpClient*>())) std::__2::__invoke[abi:ne200100]<opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0, opentelemetry::v1::ext::http::client::curl::HttpClient*>(opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0&&, opentelemetry::v1::ext::http::client::curl::HttpClient*&&) /opt/llvm-20.1/bin/../include/c++/v1/__type_traits/invoke.h:179:25 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x9b08d) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #5 void std::__2::__thread_execute[abi:ne200100]<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0, opentelemetry::v1::ext::http::client::curl::HttpClient*, 2ul>(std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0, opentelemetry::v1::ext::http::client::curl::HttpClient*>&, std::__2::__tuple_indices<2ul>) /opt/llvm-20.1/bin/../include/c++/v1/__thread/thread.h:199:3 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x9b01e) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #6 void* std::__2::__thread_proxy[abi:ne200100]<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct>>, opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0, opentelemetry::v1::ext::http::client::curl::HttpClient*>>(void*) /opt/llvm-20.1/bin/../include/c++/v1/__thread/thread.h:208:3 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x9addc) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
  Previous read of size 8 at 0x721400000e68 by main thread (mutexes: write M0):
    #0 __tsan_memcpy build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_memintrinsics.cpp:27:3 (example_otlp_http+0x12d42e) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #1 opentelemetry::v1::ext::http::client::curl::HttpOperation::Finish() /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_operation_curl.cc:363:9 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0xd3405) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #2 opentelemetry::v1::ext::http::client::curl::Session::FinishSession() /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_client_curl.cc:257:22 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x97989) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #3 opentelemetry::v1::exporter::otlp::OtlpHttpClient::cleanupGCSessions() /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:1043:29 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9da18) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #4 opentelemetry::v1::exporter::otlp::OtlpHttpClient::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:852:10 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9d8c8) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #5 opentelemetry::v1::exporter::otlp::OtlpHttpExporter::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_exporter.cc:213:24 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uexporter.so+0x731eb) (BuildId: 8851f6765aa989161be83e2d15ec997439378ec5)
    #6 opentelemetry::v1::sdk::trace::SimpleSpanProcessor::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/simple_processor.h:83:25 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x19323d) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #7 opentelemetry::v1::sdk::trace::MultiSpanProcessor::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/multi_span_processor.h:132:28 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1bc39a) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #8 opentelemetry::v1::sdk::trace::TracerContext::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/src/trace/tracer_context.cc:79:22 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1a41ea) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #9 opentelemetry::v1::sdk::trace::TracerProvider::Shutdown(std::__2::chrono::duration<long long, std::__2::ratio<1l, 1000000l>>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/src/trace/tracer_provider.cc:140:20 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1c7d78) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #10 (anonymous namespace)::CleanupTracer() /proc/self/cwd/examples/otlp/main_http.cc:207:11 (example_otlp_http+0x1b5a09) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #11 main /proc/self/cwd/examples/otlp/main_http.cc:249:3 (example_otlp_http+0x1b4e71) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
  Location is heap block of size 72 at 0x721400000e60 allocated by main thread:
    #0 malloc build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:676:5 (example_otlp_http+0x12fc40) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #1 operator new(unsigned long) build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/libcxxabi/src/stdlib_new_delete.cpp:54:15 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sostream_Slibostream_Uspan_Uexporter.so+0x1aac17) (BuildId: e6361ad18e122938fe386174989a4033122037c3)
    #2 opentelemetry::v1::ext::http::client::curl::Session::SendRequest(std::__2::shared_ptr<opentelemetry::v1::ext::http::client::EventHandler>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_client_curl.cc:208:36 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x97266) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #3 opentelemetry::v1::exporter::otlp::OtlpHttpClient::addSession(opentelemetry::v1::exporter::otlp::OtlpHttpClient::HttpSessionData&&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:1029:12 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9f893) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #4 opentelemetry::v1::exporter::otlp::OtlpHttpClient::Export(google::protobuf::Message const&, std::__2::function<bool (opentelemetry::v1::sdk::common::ExportResult)>&&, unsigned long) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:760:3 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9dedd) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #5 opentelemetry::v1::exporter::otlp::OtlpHttpClient::Export(google::protobuf::Message const&, std::__2::function<bool (opentelemetry::v1::sdk::common::ExportResult)>&&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:746:10 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9e304) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #6 opentelemetry::v1::exporter::otlp::OtlpHttpExporter::Export(std::__2::span<std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>, 18446744073709551615ul> const&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_exporter.cc:174:17 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uexporter.so+0x7304a) (BuildId: 8851f6765aa989161be83e2d15ec997439378ec5)
    #7 opentelemetry::v1::sdk::trace::SimpleSpanProcessor::OnEnd(std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>&&) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/simple_processor.h:59:20 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1930be) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #8 opentelemetry::v1::sdk::trace::MultiSpanProcessor::OnEnd(std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>&&) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/multi_span_processor.h:103:20 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1bc1bb) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #9 opentelemetry::v1::sdk::trace::Span::End(opentelemetry::v1::trace::EndSpanOptions const&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/src/trace/span.cc:221:27 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x193d11) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #10 (anonymous namespace)::SendRequest(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, bool, std::__2::unordered_map<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::hash<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::equal_to<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::allocator<std::__2::pair<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>>> const&, opentelemetry::v1::trace::TraceId, opentelemetry::v1::trace::SpanId) /proc/self/cwd/examples/otlp/main_http.cc:146:9 (example_otlp_http+0x1b73da) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #11 (anonymous namespace)::ReportSpan(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, bool, std::__2::unordered_map<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::hash<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::equal_to<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::allocator<std::__2::pair<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>>> const&) /proc/self/cwd/examples/otlp/main_http.cc:177:7 (example_otlp_http+0x1b54fe) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #12 main /proc/self/cwd/examples/otlp/main_http.cc:247:3 (example_otlp_http+0x1b4e6a) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
  Mutex M0 (0x725800000210) created at:
    #0 pthread_mutex_init build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1345:3 (example_otlp_http+0x1334fc) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #1 std::__2::recursive_mutex::recursive_mutex() build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/build_jobs_dir/tools/clang/stage2-bins/include/c++/v1/__thread/support/pthread.h:62:10 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x104adb) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #2 opentelemetry::v1::exporter::otlp::OtlpHttpExporter::OtlpHttpExporter(opentelemetry::v1::exporter::otlp::OtlpHttpExporterOptions const&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_exporter.cc:45:24 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uexporter.so+0x71f4a) (BuildId: 8851f6765aa989161be83e2d15ec997439378ec5)
    #3 (anonymous namespace)::InitTracer(opentelemetry::v1::exporter::otlp::OtlpHttpExporterOptions const&, opentelemetry::v1::sdk::resource::Resource) /proc/self/cwd/examples/otlp/main_http.cc:81:11 (example_otlp_http+0x1b50f8) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #4 main /proc/self/cwd/examples/otlp/main_http.cc:244:3 (example_otlp_http+0x1b4e2c) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
  Thread T1 (tid=37535, running) created by main thread at:
    #0 pthread_create build_jobs_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-TencentOS-linux-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1041:3 (example_otlp_http+0x131b7a) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #1 std::__2::__libcpp_thread_create[abi:ne200100](unsigned long*, void* (*)(void*), void*) /opt/llvm-20.1/bin/../include/c++/v1/__thread/support/pthread.h:182:10 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0xc3649) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #2 std::__2::thread::thread<opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0, opentelemetry::v1::ext::http::client::curl::HttpClient*, 0>(opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread()::$_0&&, opentelemetry::v1::ext::http::client::curl::HttpClient*&&) /opt/llvm-20.1/bin/../include/c++/v1/__thread/thread.h:218:14 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x98a69) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #3 opentelemetry::v1::ext::http::client::curl::HttpClient::MaybeSpawnBackgroundThread() /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_client_curl.cc:445:32 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x974c3) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #4 opentelemetry::v1::ext::http::client::curl::Session::SendRequest(std::__2::shared_ptr<opentelemetry::v1::ext::http::client::EventHandler>) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_client_curl.cc:231:18 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sext_Ssrc_Shttp_Sclient_Scurl_Slibhttp_Uclient_Ucurl.so+0x972c1) (BuildId: d1b940e8ad0a712e1fc9074c01794c3d4a935985)
    #5 opentelemetry::v1::exporter::otlp::OtlpHttpClient::addSession(opentelemetry::v1::exporter::otlp::OtlpHttpClient::HttpSessionData&&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:1029:12 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9f893) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #6 opentelemetry::v1::exporter::otlp::OtlpHttpClient::Export(google::protobuf::Message const&, std::__2::function<bool (opentelemetry::v1::sdk::common::ExportResult)>&&, unsigned long) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:760:3 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9dedd) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #7 opentelemetry::v1::exporter::otlp::OtlpHttpClient::Export(google::protobuf::Message const&, std::__2::function<bool (opentelemetry::v1::sdk::common::ExportResult)>&&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_client.cc:746:10 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uclient.so+0x9e304) (BuildId: ac74d56a0e00f6783b3bd1d5f1434bd214067e5d)
    #8 opentelemetry::v1::exporter::otlp::OtlpHttpExporter::Export(std::__2::span<std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>, 18446744073709551615ul> const&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/exporters/otlp/src/otlp_http_exporter.cc:174:17 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Sexporters_Sotlp_Slibotlp_Uhttp_Uexporter.so+0x7304a) (BuildId: 8851f6765aa989161be83e2d15ec997439378ec5)
    #9 opentelemetry::v1::sdk::trace::SimpleSpanProcessor::OnEnd(std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>&&) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/simple_processor.h:59:20 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1930be) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #10 opentelemetry::v1::sdk::trace::MultiSpanProcessor::OnEnd(std::__2::unique_ptr<opentelemetry::v1::sdk::trace::Recordable, std::__2::default_delete<opentelemetry::v1::sdk::trace::Recordable>>&&) /proc/self/cwd/bazel-out/k8-dbg-tsan/bin/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/_virtual_includes/headers/opentelemetry/sdk/trace/multi_span_processor.h:103:20 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x1bc1bb) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #11 opentelemetry::v1::sdk::trace::Span::End(opentelemetry::v1::trace::EndSpanOptions const&) /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/sdk/src/trace/span.cc:221:27 (libexternal_S_Umain~_Urepo_Urules~io_Uopentelemetry_Ucpp_Ssdk_Ssrc_Strace_Slibtrace.so+0x193d11) (BuildId: 4deaf8000ad693fc792682b3bb3e72607b815f8e)
    #12 (anonymous namespace)::SendRequest(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, bool, std::__2::unordered_map<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::hash<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::equal_to<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::allocator<std::__2::pair<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>>> const&, opentelemetry::v1::trace::TraceId, opentelemetry::v1::trace::SpanId) /proc/self/cwd/examples/otlp/main_http.cc:146:9 (example_otlp_http+0x1b73da) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #13 (anonymous namespace)::ReportSpan(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&, bool, std::__2::unordered_map<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>, std::__2::hash<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::equal_to<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>, std::__2::allocator<std::__2::pair<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>>> const&) /proc/self/cwd/examples/otlp/main_http.cc:177:7 (example_otlp_http+0x1b54fe) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
    #14 main /proc/self/cwd/examples/otlp/main_http.cc:247:3 (example_otlp_http+0x1b4e6a) (BuildId: 05f5fe2bf2de225997c763902e8431686751dffb)
SUMMARY: ThreadSanitizer: data race /proc/self/cwd/external/_main~_repo_rules~io_opentelemetry_cpp/ext/src/http/client/curl/http_operation_curl.cc:417:36 in opentelemetry::v1::ext::http::client::curl::HttpOperation::Cleanup()
==================
ThreadSanitizer: reported 1 warnings
```

### PR DESCRIPTION
**Pull request by owent**
Fixes #3530 

## Changes

- It's OK when `callback_thread` has data race in `HttpOperation`. So just ignore it.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: ext/src/http/client/curl/http_operation_curl.cc [hunk 1]
```diff
@@ -47,6 +47,28 @@ namespace client
 namespace curl
 {
```
[the remark this answers is not in the document]
Comment (owent) [reply ext/src/http/client/curl/http_operation_curl.cc:49]: anonymous namespace will break the friend access.

File: ext/src/http/client/curl/http_operation_curl.cc [hunk 2]
```diff
@@ -47,6 +47,28 @@ namespace client
...
 
+class HttpOperationAccessor
+{
+public:
+  OPENTELEMETRY_SANITIZER_NO_THREAD static std::thread::id GetThreadId(
+      const HttpOperation::AsyncData &async_data)
+  {
+#if !(defined(OPENTELEMETRY_HAVE_THREAD_SANITIZER) && OPENTELEMETRY_HAVE_THREAD_SANITIZER)
```
Comment (ThomsonTan) [inline ext/src/http/client/curl/http_operation_curl.cc:56]: Since the race condition is Ok here, is it possible to disable the repo in the callsite, instead of add separated guard just for thread sanitizer?

Comment (owent) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: Sorry, but I don't understand the points. As I see it, `__attribute__((no_sanitize_thread))` applies only to functions. The data race on `std::this_thread::get_id()` is acceptable here since it's just used to prevent recursive waiting during `HttpOperation` destruction. Therefore, I couldn't find a way to disable it at the call site.

Comment (ThomsonTan) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: Ok. It makes sense then.

Comment (marcalff) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: @owent 

I do not understand the ifdef logic here, in particular the NOT ("!").

When `OPENTELEMETRY_HAVE_THREAD_SANITIZER` is not defined, the atomic fence is added, so the fence is added in the production code, but not present in tsan builds ?

I would expect the opposite if this is a work around for tsan.

Also, could `callback_thread` be changed to an atomic instead, it would be simpler.

Please clarify.

**Review by marcalff — COMMENTED** [review]
Thanks for the patch.

See some questions on the ifdef logic.

File: ext/src/http/client/curl/http_operation_curl.cc (hunk 2 above)
Comment (owent) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: `std::thread::id` is not a integer, so we can not simply use atomic here.
`atomic_thread_fence` can not be used when tsan is used.

The primary purpose of this variable is to prevent a thread from waiting on itself when destroying `HttpOperation`. While not strictly necessary, it can expedite waking the caller during shutdown on another thread.

Comment (marcalff) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: I see.

So this patch is not about adding a work around to silence tsan, as I understood initially.

It is about fixing a race condition in the production code.

Now, the "ifdef not tsan" is because the added code for the fix (atomic fence) is not supported by tsan.

@owent Is this description correct ?

Comment (owent) [reply ext/src/http/client/curl/http_operation_curl.cc:56]: Yes. Without atomic fence here may just loss the notification to the waiter, but all exporters who use this class will retry the checking sooner, so it's safe to just ignore this fence.
