### PR TITLE
Fix 1585 - Multiple cumulative metric collections without measurement recording.

### LINKED ISSUE #1585: Cumulative Metric Exam
**Describe your environment** 
https://github.com/open-telemetry/opentelemetry-cpp; main branch

**Steps to reproduce**
Modify https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/common/metrics_foo_library/foo_library.cc:62 to increase sleep to 2seconds
To run:
./metrics_ostream_example counter
**What is the expected behavior?**
What did you expect to see?
Metric Counter should accumulate values, when aggregation is Cumulative.
So even if for some interval there are no samples, then sum should be total sum and not 0

**What is the actual behavior?**
What did you see instead?
When there are no samples in some collecting intervals, the value resets

**Additional context**
Current Output:
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Aug 30 14:35:15 2022
  end time      : Tue Aug 30 14:35:16 2022
  instrument name       : ostream_metric_example_counter
  description   :
  unit          :
  type          : SumPointData
  value         : **5**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Aug 30 14:35:16 2022
  end time      : Tue Aug 30 14:35:17 2022
  instrument name       : ostream_metric_example_counter
  description   :
  unit          :
  type          : SumPointData
  value         : **10**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Aug 30 14:35:17 2022
  end time      : Tue Aug 30 14:35:18 2022
  instrument name       : ostream_metric_example_counter
  description   :
  unit          :
  type          : SumPointData
  value         : **0**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Aug 30 14:35:18 2022
  end time      : Tue Aug 30 14:35:19 2022
  instrument name       : ostream_metric_example_counter
  description   :
  unit          :
  type          : SumPointData
  value         : **5**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1585 

## Changes

In case cumulative metric collection is done without any measurement recorded in between, the same metrics should be returned. Merge was not happening properly if there is no unreported metrics. This is fixed now. Also added the tests to validate.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by tauseef-ah** [comment]
Hi lalit, I just tested your changes, and I observe the when counter metrics are not sent from application side, then the metrics are displayed as 0. However, when the metrics values are sent the counter correctly accumulates from past data:
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Thu Sep  1 06:41:35 2022
  end time      : Thu Sep  1 06:41:36 2022
  instrument name       : ostream_metric_example
  description   : description
  unit          :
  type          : SumPointData
  value         : **107**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Thu Sep  1 06:41:36 2022
  end time      : Thu Sep  1 06:41:37 2022
  instrument name       : ostream_metric_example
  description   : description
  unit          :
  type          : SumPointData
  value         : **0**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Thu Sep  1 06:41:37 2022
  end time      : Thu Sep  1 06:41:38 2022
  instrument name       : ostream_metric_example
  description   : description
  unit          :
  type          : SumPointData
  value         : **108**
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.6.0
}

**Comment by lalitb** [comment]
@tauseef-ah  - Thanks for testing this. How can I reproduce the scenario? 

Record(2) -> Record(3) -> Collect(5) -> Collect(5) -> Record(4) -> Collect(9) -> Collect(9)

I tested something like the above and got the expected result with this PR.

**Comment by tauseef-ah** [comment]
hi @lalitb , sorry there seems to have been an issue with us picking the wrong binaries at runtime. This solution works fine for us too. Thanks

File: sdk/src/metrics/state/temporal_metric_storage.cc [hunk 1]
```diff
@@ -88,20 +91,20 @@ bool TemporalMetricStorage::buildMetrics(CollectorHandle *collector,
...
-        }
-        else
-        {
-          merged_metrics->Set(
-              attributes, DefaultAggregation::CreateAggregation(instrument_descriptor_, nullptr));
-        }
-        return true;
-      });
+      last_aggr_hashmap->GetAllEnteries(
+          [&merged_metrics, this](const MetricAttributes &attributes, Aggregation &aggregation) {
```
Comment (ThomsonTan) [inline sdk/src/metrics/state/temporal_metric_storage.cc:95]: Is this jus reformat?

Comment (lalitb) [reply sdk/src/metrics/state/temporal_metric_storage.cc:95]: yes, this is done by clang-format. The only changes are lines 103, and 104 below. To handle the `else` scenario when there are no measurements recorded since the last collection.

File: sdk/test/metrics/sync_metric_storage_test.cc [hunk 2]
```diff
@@ -105,6 +105,30 @@ TEST_P(WritableMetricStorageTestFixture, LongSumAggregation)
     expected_total_put_requests = 0;
   }
 
+  // collect one more time.
+  collection_ts    = std::chrono::system_clock::now();
+  count_attributes = 0;
```
Comment (ThomsonTan) [inline sdk/test/metrics/sync_metric_storage_test.cc:110]: Is this variable used?

Comment (lalitb) [reply sdk/test/metrics/sync_metric_storage_test.cc:110]: Good catch. It should have been used. Have added the validation to check if the collect() gets metrics with all the attributes. In case of Delta temporarily, for simultaneous collections only the first collect() will get the metrics, the subsequent collect() will return entry. Have added that validation too.

**Review by ThomsonTan — APPROVED** [review]
