### PR TITLE
[EXPORTER] handling of invalid ports in UrlParser

### LINKED ISSUE #3138: URL parser throws an exception
When parsing `https://https://example.com/some/path`, the URL parser throws an exception.

The expected result is to return a parse error instead.

```
diff --git a/ext/test/http/url_parser_test.cc b/ext/test/http/url_parser_test.cc
index aceb4396..118320e4 100644
--- a/ext/test/http/url_parser_test.cc
+++ b/ext/test/http/url_parser_test.cc
@@ -18,6 +18,13 @@ inline const char *BoolToString(bool b)
 TEST(UrlParserTests, BasicTests)
 {
   std::map<std::string, std::map<std::string, std::string>> urls_map{
+      {"https://https://example.com/some/path",
+       {{"host", "www.abc.com"},
+        {"port", "80"},
+        {"scheme", "http"},
+        {"path", "/"},
+        {"query", ""},
+        {"success", "true"}}},
       {"www.abc.com",
        {{"host", "www.abc.com"},
         {"port", "80"},
```

```
[malff@malff-desktop build-otelcpp-abiv1]$ ./ext/test/http/url_parser_test
Running main() from /builddir/build/BUILD/googletest-release-1.11.0/googletest/src/gtest_main.cc
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from UrlParserTests
[ RUN      ] UrlParserTests.BasicTests
unknown file: Failure
C++ exception with description "stoi" thrown in the test body.
[  FAILED  ] UrlParserTests.BasicTests (0 ms)
[----------] 1 test from UrlParserTests (0 ms total)

[----------] 1 test from UrlDecoderTests
[ RUN      ] UrlDecoderTests.BasicTests
[       OK ] UrlDecoderTests.BasicTests (0 ms)
[----------] 1 test from UrlDecoderTests (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] UrlParserTests.BasicTests

 1 FAILED TEST
```

### PR DESCRIPTION
**Pull request by sjinks**
Fixes #3138

## Changes

This PR adds handling of invalid ports to UrlParser.

Previously, invalid ports caused an exception; this PR updated the code so as not to throw exceptions and set `success_` to `false`.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: ext/include/opentelemetry/ext/http/common/url_parser.h [hunk 1]
```diff
@@ -88,8 +89,11 @@ class UrlParser
       path_ = std::string("/");  // use default path
       if (is_port)
       {
-        port_ = static_cast<uint16_t>(
-            std::stoi(std::string(url_.begin() + cpos, url_.begin() + url_.length())));
+        std::string port_str(
+            url_.begin() + static_cast<std::string::difference_type>(cpos),
+            url_.begin() + static_cast<std::string::difference_type>(url_.length()));
```
Comment (sjinks) [inline ext/include/opentelemetry/ext/http/common/url_parser.h:94]: `static_cast<>` is because "Narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'difference_type' (aka 'long') is implementation-defined"

See also: https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/narrowing-conversions.html

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

**Review by lalitb — APPROVED** [review]
