### PR TITLE
[SDK] env var durations non conforming to spec

### LINKED ISSUE #4019: [SDK] env var durations non corforming to spec
**Steps to reproduce**
If I set [`OTEL_METRIC_EXPORT_INTERVAL`](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#periodic-exporting-metricreader) the spec they this are ms, with this SDK this are seconds. 
You get no warnings, nothing. You only wounder why the metrics export does not work (every 15 secs gets every 4.1 hours)

**What is the expected behavior?**
Do what the spec say. Or print a warning and/or change the documentation. 

<sub>**Tip**: [React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #4019

## Changes

Please provide a brief description of the changes here.

* Environment variables for duration should be interpreted in milliseconds, not seconds

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [X] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by marcalff** [comment]
@open-telemetry/cpp-approvers 

This is a breaking change, but really needs to be fixed in my opinion.

With declarative configuration in yaml, the same variable:
- without yaml, used directly, leads to seconds (currently broken)
- with yaml, used with env var substitution, leads to milliseconds (correct)

File: sdk/src/common/env_variables.cc [hunk 1]
```diff
@@ -159,11 +159,8 @@ static bool GetTimeoutFromString(const char *input, std::chrono::system_clock::d
 
   if (unit == "")
   {
-    // TODO: The spec says milliseconds, but opentelemetry-cpp implemented
-    // seconds by default. Fixing this is a breaking change.
-
     value = std::chrono::duration_cast<std::chrono::system_clock::duration>(
```
Comment (ThomsonTan) [inline sdk/src/common/env_variables.cc:165]: Rather than removing the TODO entirely, could you leave a one-liner pointing to the spec and the release that flipped the default? Preserves the "why" for future code search.

Comment (marcalff) [reply sdk/src/common/env_variables.cc:165]: It is preserved in the unit test.

Comment (marcalff) [reply sdk/src/common/env_variables.cc:165]: Preserved and updated the existing comment in the code, in addition to the test.

File: CHANGELOG.md [hunk 2]
```diff
@@ -104,6 +107,34 @@ Important changes:
...
+  * When parsing environment variables that represent durations,
+    for example `OTEL_METRIC_EXPORT_INTERVAL=15000`,
+    the code interpreted the value, `15000`,
+    in seconds instead of milliseconds per the specifications.
+  * Parsing duration has been fixed to use the proper units.
+  * As a consequence, every duration environment variable set
+    is now interpreted differently, which is a breaking change.
+  * For example, `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=30` meant 30 seconds
+    before, and now means 30 milliseconds.
+    To preserve the same behavior, existing values must be adjusted,
```
Comment (dbarker) [inline CHANGELOG.md:138]: Consider documenting the explicit units approach here too `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=30s`

File: CHANGELOG.md [hunk 3]
```diff
@@ -104,6 +107,34 @@ Important changes:
 
   * Bazel now always builds with ENABLE_OTLP_RETRY_PREVIEW.
 
+Breaking changes:
+
+* [SDK] env var durations non conforming to spec
+  [#4020](https://github.com/open-telemetry/opentelemetry-cpp/pull/4020)
+
+  * When parsing environment variables that represent durations,
+    for example `OTEL_METRIC_EXPORT_INTERVAL=15000`,
```
Comment (dbarker) [inline CHANGELOG.md:130]: There is some redundancy with examples, consider removing one.

File: CHANGELOG.md [hunk 4]
```diff
@@ -104,6 +107,34 @@ Important changes:
...
+    the code interpreted the value, `15000`,
+    in seconds instead of milliseconds per the specifications.
+  * Parsing duration has been fixed to use the proper units.
```
Comment (dbarker) [inline CHANGELOG.md]: consider "proper units" -> "required units of milliseconds when left unspecified". We should be clear that interpretation of durations with explicit units (ie: 30s ..) will remain working as before.

**Review by dbarker — APPROVED** [review]
Looks good. Agree we should fix it. Please see some suggestions on the changelog entry.

File: CHANGELOG.md (hunk 2 above)
Comment (dbarker) [reply CHANGELOG.md:138]: Rereading the spec I don't see any mention of other units for durations configured by environment variables.   Should we support explicit units other than the default milliseconds?

https://opentelemetry.io/docs/specs/otel/configuration/common/#duration

File: CHANGELOG.md [hunk 5]
```diff
@@ -104,6 +107,34 @@ Important changes:
...
+  * As a consequence, every duration environment variable set
```
Comment (lalitb) [inline CHANGELOG.md:134]: > every duration environment variable set is now interpreted differently

This statement too broad, as only unitless values change; explicit suffix values like 20s, 250ms still behave same.

File: CHANGELOG.md [hunk 6]
```diff
@@ -82,6 +82,9 @@ Increment the:
 * [CODE HEALTH] Fix clang-tidy narrowing-conversions warnings in sync_instruments
   [#4013](https://github.com/open-telemetry/opentelemetry-cpp/pull/4013)
 
+* [SDK] env var durations non corforming to spec
```
Comment (lalitb) [inline CHANGELOG.md]:
```suggestion
* [SDK] env var durations non conforming to spec
```

**Review by lalitb — APPROVED** [review]

File: sdk/src/common/env_variables.cc [hunk 7]
```diff
@@ -159,11 +159,11 @@ static bool GetTimeoutFromString(const char *input, std::chrono::system_clock::d
 
   if (unit == "")
   {
-    // TODO: The spec says milliseconds, but opentelemetry-cpp implemented
-    // seconds by default. Fixing this is a breaking change.
+    // The spec says milliseconds, but opentelemetry-cpp implemented
+    // seconds by default, up to opentelemetry-cpp 1.26.0.
 
     value = std::chrono::duration_cast<std::chrono::system_clock::duration>(
```
Comment (ThomsonTan) [inline sdk/src/common/env_variables.cc:165]: Given this is a silent 1000x behavior change, could a warning be logged a warning with `OTEL_INTERNAL_LOG_WARN`?

File: CHANGELOG.md (hunk 2 above)
Comment (marcalff) [reply CHANGELOG.md:138]: Units are a otelcpp extension.

Reworded for clarity.

File: CHANGELOG.md (hunk 3 above)
Comment (marcalff) [reply CHANGELOG.md:130]: Reworded for clarity.

File: CHANGELOG.md (hunk 5 above)
Comment (marcalff) [reply CHANGELOG.md:134]: Reworded for clarity.

File: sdk/src/common/env_variables.cc (hunk 7 above)
Comment (marcalff) [reply sdk/src/common/env_variables.cc:165]: If we print a warning, how would people get rid of it after fixing the value ?

This is covered in the CHANGELOG and will be in the release notes, but I don't see how we can raise a warning for this.

File: CHANGELOG.md (hunk 4 above)
Comment (marcalff) [reply CHANGELOG.md]: Reworded for clarity.

**Review by ThomsonTan — APPROVED** [review]
