### PR TITLE
Reorder the destructor of members in LoggerProvider and TracerProvider

### LINKED ISSUE #1244: Crash when destroy LoggerProvider and TracerProvider
**Describe your environment**

OS: Linux/CentOS 7
Compiler: GCC 4.8.5

**Steps to reproduce**

It may happen when destroy the last LoggerProvider and TracerProvider. But it only rarely happen.

**Additional context**

```bash
(gdb) info thread
  Id   Target Id         Frame 
  8    Thread 0x7f5b85538700 (LWP 17277) 0x00007f5b89c98d19 in syscall () from /lib64/libc.so.6
  7    Thread 0x7f5b84d37700 (LWP 17280) 0x00007f5b89c98d19 in syscall () from /lib64/libc.so.6
  6    Thread 0x7f5b85d39700 (LWP 17276) 0x00007f5b89c98d19 in syscall () from /lib64/libc.so.6
  5    Thread 0x7f5b89b9e8c0 (LWP 17267) 0x00007f5b8ab9f017 in pthread_join () from /lib64/libpthread.so.0
  4    Thread 0x7f5b612ce700 (LWP 31542) 0x00007f5b89c98d19 in syscall () from /lib64/libc.so.6
  3    Thread 0x7f5b60acd700 (LWP 17452) 0x00007f5b89c98d19 in syscall () from /lib64/libc.so.6
  2    Thread 0x7f5b83d35700 (LWP 17286) 0x00007f5b8aba1de2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
* 1    Thread 0x7f5b84536700 (LWP 17283) 0x00007f5b8a32ef8b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /lib64/libstdc++.so.6
```

Thread 1:
```bash
(gdb) bt
#0  0x00007f5b8a32ef8b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
#1  0x00000000023cc018 in CreateInternal<std::basic_string<char>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (arena=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/protobuf-v3.19.4/src/google/protobuf/arena.h:696
#2  Create<std::basic_string<char>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (arena=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/protobuf-v3.19.4/src/google/protobuf/arena.h:316
#3  google::protobuf::internal::ArenaStringPtr::Set (this=0x7f5b83eb57b0, default_value=<optimized out>, 
    value=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>, arena=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/protobuf-v3.19.4/src/google/protobuf/arenastring.cc:76
#4  0x00000000023cc0f2 in google::protobuf::internal::ArenaStringPtr::Set (this=<optimized out>, value=..., arena=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/protobuf-v3.19.4/src/google/protobuf/arenastring.cc:102
#5  0x00000000020c581b in set_name<std::basic_string<char> const&> (arg0=..., this=0x7f5b83eb57a0)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/build_jobs_linux/_deps/opentelemetry_cpp-v1.2.0/linux-x86_64-gnu/generated/third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.pb.h:2000
#6  opentelemetry::v1::exporter::otlp::OtlpRecordable::GetProtoInstrumentationLibrary (this=this@entry=0x8c90680)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/exporters/otlp/src/otlp_recordable.cc:70
#7  0x00000000020c76cd in opentelemetry::v1::exporter::otlp::OtlpRecordableUtils::PopulateRequest (spans=..., request=request@entry=0x7f5b83eb5890)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/exporters/otlp/src/otlp_recordable_utils.cc:270
#8  0x00000000020add5c in opentelemetry::v1::exporter::otlp::OtlpGrpcExporter::Export (this=0x8b16660, spans=...)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/exporters/otlp/src/otlp_grpc_exporter.cc:114
#9  0x00000000020f9eb9 in opentelemetry::v1::sdk::trace::BatchSpanProcessor::Export (this=this@entry=0x8af7e20, was_force_flush_called=was_force_flush_called@entry=false)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/src/trace/batch_span_processor.cc:160
#10 0x00000000020fa03a in opentelemetry::v1::sdk::trace::BatchSpanProcessor::DrainQueue (this=this@entry=0x8af7e20)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/src/trace/batch_span_processor.cc:177
#11 0x00000000020fa1b0 in opentelemetry::v1::sdk::trace::BatchSpanProcessor::DoBackgroundWork (this=0x8af7e20)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/src/trace/batch_span_processor.cc:98
#12 0x00007f5b8a325340 in ?? () from /lib64/libstdc++.so.6
#13 0x00007f5b8ab9dea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f5b89c9e9fd in clone () from /lib64/libc.so.6
```

Thread 5:

```bash
#0  0x00007f5b8ab9f017 in pthread_join () from /lib64/libpthread.so.0
#1  0x00007f5b8a325107 in std::thread::join() () from /lib64/libstdc++.so.6
#2  0x00000000020f9653 in opentelemetry::v1::sdk::trace::BatchSpanProcessor::Shutdown (this=0x8af7e20, timeout=...)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/src/trace/batch_span_processor.cc:186
#3  0x00000000020fb673 in Shutdown (timeout=..., this=0x8b4fdd0)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/multi_span_processor.h:131
#4  ~MultiSpanProcessor (this=0x8b4fdd0, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/multi_span_processor.h:139
#5  opentelemetry::v1::sdk::trace::MultiSpanProcessor::~MultiSpanProcessor (this=0x8b4fdd0, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/multi_span_processor.h:141
#6  0x00000000020f6e58 in operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/4.8.2/bits/unique_ptr.h:67
#7  ~unique_ptr (this=0x89d7958, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/unique_ptr.h:184
#8  ~TracerContext (this=0x89d7908, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/tracer_context.h:32
#9  destroy<opentelemetry::v1::sdk::trace::TracerContext> (this=<optimized out>, __p=0x89d7908) at /usr/include/c++/4.8.2/ext/new_allocator.h:124
#10 _S_destroy<opentelemetry::v1::sdk::trace::TracerContext> (__a=..., __p=0x89d7908) at /usr/include/c++/4.8.2/bits/alloc_traits.h:281
#11 destroy<opentelemetry::v1::sdk::trace::TracerContext> (__a=..., __p=0x89d7908) at /usr/include/c++/4.8.2/bits/alloc_traits.h:405
#12 std::_Sp_counted_ptr_inplace<opentelemetry::v1::sdk::trace::TracerContext, std::allocator<opentelemetry::v1::sdk::trace::TracerContext>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:407
#13 0x00000000020f69e2 in _M_release (this=0x89d78f0) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#14 ~__shared_count (this=0xc97c510, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
#15 ~__shared_ptr (this=0xc97c508, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
#16 ~shared_ptr (this=0xc97c508, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr.h:93
#17 ~Tracer (this=0xc97c4e0, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/tracer.h:26
#18 ~Tracer (this=0xc97c4e0, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/tracer.h:26
#19 std::_Sp_counted_ptr<opentelemetry::v1::sdk::trace::Tracer*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:290
#20 0x00000000020f6d2f in _M_release (this=0xb739080) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#21 ~__shared_count (this=0xbc76e48, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
#22 ~__shared_ptr (this=0xbc76e40, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
#23 ~shared_ptr (this=0xbc76e40, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr.h:93
#24 _Destroy<std::shared_ptr<opentelemetry::v1::sdk::trace::Tracer> > (__pointer=0xbc76e40) at /usr/include/c++/4.8.2/bits/stl_construct.h:93
#25 __destroy<std::shared_ptr<opentelemetry::v1::sdk::trace::Tracer>*> (__last=<optimized out>, __first=0xbc76e40) at /usr/include/c++/4.8.2/bits/stl_construct.h:103
#26 _Destroy<std::shared_ptr<opentelemetry::v1::sdk::trace::Tracer>*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_construct.h:126
#27 _Destroy<std::shared_ptr<opentelemetry::v1::sdk::trace::Tracer>*, std::shared_ptr<opentelemetry::v1::sdk::trace::Tracer> > (__last=0xbc76e50, __first=0xbc76e30)
    at /usr/include/c++/4.8.2/bits/stl_construct.h:151
#28 ~vector (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:415
#29 ~TracerProvider (this=<optimized out>, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/tracer_provider.h:25
#30 opentelemetry::v1::sdk::trace::TracerProvider::~TracerProvider (this=<optimized out>, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/packages/opentelemetry-cpp-v1.2.0/sdk/include/opentelemetry/sdk/trace/tracer_provi
#31 0x00000000013eed69 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x89cfe90) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#32 0x00000000014b0d0a in ~shared_ptr (this=0x7ffdbd793870, __in_chrg=<optimized out>)
    at /data2/devops/workspace/p-50619563e9c746fca28a7a6ab5f648d6/src/repo/Server/dev/third_party/install/linux-x86_64-gnu/include/opentelemetry/nostd/shared_ptr.h:98
#33 rpc::telemetry::_opentelemetry_cleanup_global_provider (app=...)
```

This may related to destructing order of members in `LoggerProvider` and `Logger`.
And also, I need Shutdown myself sometimes but the destructor of `MultiSpanProcessor` and `MultiLogProcessor` will shutdown again and them will cause crash when `worker_thread_.join()` is called twice in `BatchLogProcessor` and `BatchSpanProcessor`.

### PR DESCRIPTION
**Pull request by owent**
…r. It's safe to shutdown multiple times.(Fix #1244)

Signed-off-by: owentou <owentou@tencent.com>

Fixes #1244 

## Changes

1. Reorder the destructor of members in LoggerProvider and TracerProvider.
2. It's safe to shutdown multiple times.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: sdk/include/opentelemetry/sdk/logs/logger.h [hunk 1]
```diff
@@ -67,9 +67,10 @@ class Logger final : public opentelemetry::logs::Logger
   // The name of this logger
   std::string logger_name_;
 
-  // The logger context of this Logger. Uses a weak_ptr to avoid cyclic dependency issues the with
-  std::weak_ptr<LoggerContext> context_;
   std::unique_ptr<instrumentationlibrary::InstrumentationLibrary> instrumentation_library_;
```
Comment (esigo) [inline sdk/include/opentelemetry/sdk/logs/logger.h:70]: The order of initialization in the ctor has to be changed too.

File: sdk/test/logs/logger_provider_sdk_test.cc [hunk 2]
```diff
@@ -103,4 +104,30 @@ TEST(LoggerProviderSDK, GetResource)
   LoggerProvider lp{nullptr, resource};
   ASSERT_EQ(nostd::get<std::string>(lp.GetResource().GetAttributes().at("key")), "value");
 }
+
+TEST(LoggerProviderSDK, Shutdown)
+{
+  std::unique_ptr<SimpleLogProcessor> processor(new SimpleLogProcessor(nullptr));
```
Comment (esigo) [inline sdk/test/logs/logger_provider_sdk_test.cc:110]: we shouldn't pass null exporter.

Comment (owent) [reply sdk/test/logs/logger_provider_sdk_test.cc:110]: This is just the same as https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/test/trace/tracer_provider_test.cc#L80 and https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/test/trace/tracer_provider_test.cc#L91 . Is there NoopExporter right now?

File: sdk/include/opentelemetry/sdk/logs/logger.h (hunk 1 above)
Comment (owent) [reply sdk/include/opentelemetry/sdk/logs/logger.h:72]: Fixed.

File: sdk/test/logs/logger_provider_sdk_test.cc (hunk 2 above)
Comment (esigo) [reply sdk/test/logs/logger_provider_sdk_test.cc:110]: We don't handle null exporter in many places. But you are right it's not new to use null in tests. We have no `NoopExporter` AFIK.

**Comment by owent** [comment]
It's too late on my timezone. I will solve the failed jobs tomorrow.

File: sdk/include/opentelemetry/sdk/logs/logger_provider.h [hunk 3]
```diff
@@ -107,14 +109,20 @@ class LoggerProvider final : public opentelemetry::logs::LoggerProvider
    */
   const opentelemetry::sdk::resource::Resource &GetResource() const noexcept;
 
-private:
-  // A pointer to the processor stored by this logger provider
-  std::shared_ptr<sdk::logs::LoggerContext> context_;
+  /**
+   * Shutdown the log processor associated with this log provider.
+   */
+  bool Shutdown() noexcept;
```
Comment (esigo) [inline sdk/include/opentelemetry/sdk/logs/logger_provider.h:115]: shouldn't we have timeout here?

File: sdk/test/logs/simple_log_processor_test.cc [hunk 4]
```diff
@@ -116,8 +116,6 @@ TEST(SimpleLogProcessorTest, ShutdownCalledOnce)
   EXPECT_EQ(true, processor.Shutdown());
   EXPECT_EQ(1, num_shutdowns);
```
Comment (esigo) [inline sdk/test/logs/simple_log_processor_test.cc:118]: So it's not ok to call `Shutdown` twice?

File: sdk/include/opentelemetry/sdk/logs/logger_provider.h (hunk 3 above)
Comment (owent) [reply sdk/include/opentelemetry/sdk/logs/logger_provider.h:115]: The Shutdown of tracer privoder do not have timeour.I think they should have the same arguments.

File: sdk/test/logs/simple_log_processor_test.cc (hunk 4 above)
Comment (owent) [reply sdk/test/logs/simple_log_processor_test.cc:118]: Sorry,I missed it. It should be safe to call `Shutdown` twice and it should only call `exporter.Shutdown` only once. I have already push the commit for this check.

**Review by esigo — APPROVED** [review]
LGTM
Thanks for the PR.

**Review by lalitb — APPROVED** [review]

**Comment by esigo** [comment]
@owent could you please rebase?

File: ext/test/http/curl_http_test.cc [hunk 5]
```diff
@@ -291,7 +291,9 @@ TEST_F(BasicCurlHttpTests, SendGetRequestSyncTimeout)
   auto result             = http_client.Get("http://222.222.222.200:19000/get/", m1);
   EXPECT_EQ(result, false);
 
-  EXPECT_EQ(result.GetSessionState(), http_client::SessionState::ConnectFailed);
+  // When network is under proxy, it may cennect success but closed by peer when send data
```
Comment (ThomsonTan) [inline ext/test/http/curl_http_test.cc:294]:
```suggestion
  // When network is under proxy, it may connect success but closed by peer when send data
```

File: sdk/include/opentelemetry/sdk/logs/logger.h [hunk 6]
```diff
@@ -67,9 +67,10 @@ class Logger final : public opentelemetry::logs::Logger
   // The name of this logger
   std::string logger_name_;
 
-  // The logger context of this Logger. Uses a weak_ptr to avoid cyclic dependency issues the with
-  std::weak_ptr<LoggerContext> context_;
+  // order of declaration is important here - instrumentation library should destroy after
+  // logger-context.
   std::unique_ptr<instrumentationlibrary::InstrumentationLibrary> instrumentation_library_;
+  std::shared_ptr<LoggerContext> context_;
```
Comment (ThomsonTan) [inline sdk/include/opentelemetry/sdk/logs/logger.h:73]: Is cyclic dependency still an issue here as it changes `weak_ptr` to `shared_ptr`?

File: sdk/src/logs/multi_log_processor.cc [hunk 7]
```diff
@@ -129,10 +129,8 @@ bool MultiLogProcessor::Shutdown(std::chrono::microseconds timeout) noexcept
   }
   for (auto &processor : processors_)
   {
-    if (!processor->Shutdown(std::chrono::duration_cast<std::chrono::microseconds>(timeout_ns)))
-    {
-      result = false;
-    }
+    result |=
```
Comment (ThomsonTan) [inline sdk/src/logs/multi_log_processor.cc:132]: Probably `||=` instead of `|=` operator?

Comment (ThomsonTan) [reply sdk/src/logs/multi_log_processor.cc:132]: Never mind, seems `||=` is not a valid operator.

File: sdk/src/trace/batch_span_processor.cc [hunk 8]
```diff
@@ -180,11 +180,16 @@ void BatchSpanProcessor::DrainQueue()
...
-  worker_thread_.join();
-  if (exporter_ != nullptr)
+  if (worker_thread_.joinable())
+  {
+    cv_.notify_one();
+    worker_thread_.join();
+  }
+
+  // Should only shutdown exporter ONCE.
+  if (!already_shutdown && exporter_ != nullptr)
```
Comment (ThomsonTan) [inline sdk/src/trace/batch_span_processor.cc:192]: Is showing down is going, later call to `Shutdown` will just return true even if the previous `Shutdown` has not been completed?

File: sdk/include/opentelemetry/sdk/logs/logger.h (hunk 6 above)
Comment (owent) [reply sdk/include/opentelemetry/sdk/logs/logger.h:73]: There is no cyclic dependency right now.It's only be hold in `Logger` and `LoggerProvider` and `Logger` is only hold by `LoggerProvider`.

File: sdk/src/logs/multi_log_processor.cc (hunk 7 above)
Comment (owent) [reply sdk/src/logs/multi_log_processor.cc:132]: This is the same as `MultiSpanProcessor`. Maybe we should only check the timeout and always return true when it do not reach timeout.
I have added `DurationUtil` to fix the overflow problem when using and converting duration types in #1209 . We can modify `Shutdown` and `ForceFlush` later.

File: sdk/src/trace/batch_span_processor.cc (hunk 8 above)
Comment (owent) [reply sdk/src/trace/batch_span_processor.cc:193]: Yes and thanks, it's definitely a problem.I add a mutex lock to prevent this.

**Comment by owent** [comment]
> @owent could you please rebase?

Done

**Review by ThomsonTan — APPROVED** [review]
