### PR TITLE
[SDK] Reset TraceFlags::IsSampled bit on sampler Decision::DROP

### LINKED ISSUE #3725: Child spans inherit the parent’s TraceFlags::kIsSampled bit even when the active sampler returns Decision::DROP
**Describe your environment**  
Ubuntu22.04 
OpenTelemetry-cpp v1.22.0

**Steps to reproduce**
1. Process1: Start a span, and set it to active, as parent, propogate(IsSampled=true)
2. Process2: Start a child span, with custom sampler, which returns Decision::DROP
3. Check the child span trace flag, it would be true

**What is the expected behavior?**
Per the spec, TraceFlags::kIsSampled must reflect the sampler decision. 
Dropped spans should have the sampled bit unset.

**What is the actual behavior?**
The child span always get the same `IsSampled()=true` if the parent is sampled, no matter what the custom sampler returns.

**Root Cause**
The code copies the parent’s flags (see [this line](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/trace/tracer.cc#L101)) and only sets the sampled bit when ShouldSample returns RECORD_AND_SAMPLE(see [this line](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/trace/tracer.cc#L117)). It never clears the bit for DROP/RECORD_ONLY. When a drop decision occurs, the SDK still creates a SpanContext with kIsSampled set and wraps it in a NoopSpan, so span->GetContext().IsSampled() remains true.

<sub>**Tip**: [React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by marcalff**
Fixes #3725

## Changes

Please provide a brief description of the changes here.

* When a sampler returns Decision::DROP or Decision::RECORD_ONLY, clear the trace sample flag, per specs.

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [X] Unit tests have been added
* [X] Changes in public API reviewed

### CODE REVIEW

File: sdk/test/trace/tracer_test.cc [hunk 1]
```diff
@@ -1331,3 +1373,32 @@ TEST(Tracer, SpanCleanupWithScope)
   }
   EXPECT_EQ(4, span_data->GetSpans().size());
 }
+
+TEST(Tracer, SpanSamplerDecision)
+{
+  InMemorySpanExporter *exporter              = new InMemorySpanExporter();
```
Comment (dbarker) [inline sdk/test/trace/tracer_test.cc:1379]: nit - prefer make_unique/make_shared in place of new.
