### PR TITLE
Fix Observable Counters/UpDownCounters 

### LINKED ISSUE #2296: Observable Counters/UpDownCounters Report Incorrect Values
**Environment**
Opentelemetry-cpp v1.9.0 on CentOS 7

**Problem**
Any Observable Counters/UpDownCounters report incorrect values if the initial observation value is non-zero.

**Steps to reproduce**
```
#include "opentelemetry/exporters/ostream/metric_exporter.h"
#include "opentelemetry/metrics/provider.h"
#include "opentelemetry/sdk/metrics/aggregation/default_aggregation.h"
#include "opentelemetry/sdk/metrics/aggregation/histogram_aggregation.h"
#include "opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h"
#include "opentelemetry/sdk/metrics/meter.h"
#include "opentelemetry/sdk/metrics/meter_provider.h"
#include <memory>
#include <thread>

namespace metric_sdk = opentelemetry::sdk::metrics;
namespace common = opentelemetry::common;
namespace exportermetrics = opentelemetry::exporter::metrics;
namespace metrics_api = opentelemetry::metrics;
namespace nostd = opentelemetry::nostd;

int value = 3;

void InitMetrics(const std::string &name) {
    std::unique_ptr<metric_sdk::PushMetricExporter> exporter{
        new exportermetrics::OStreamMetricExporter};

    std::string version{"1.2.0"};
    std::string schema{"https://opentelemetry.io/schemas/1.2.0"};

    // Initialize and set the global MeterProvider
    metric_sdk::PeriodicExportingMetricReaderOptions options;
    options.export_interval_millis = std::chrono::milliseconds(5000);
    options.export_timeout_millis = std::chrono::milliseconds(500);
    std::unique_ptr<metric_sdk::MetricReader> reader{
        new metric_sdk::PeriodicExportingMetricReader(std::move(exporter),
                                                      options)};
    auto provider = std::shared_ptr<metrics_api::MeterProvider>(
        new metric_sdk::MeterProvider());
    auto p = std::static_pointer_cast<metric_sdk::MeterProvider>(provider);
    p->AddMetricReader(std::move(reader));

    metrics_api::Provider::SetMeterProvider(provider);
}

void CleanupMetrics() {
    std::shared_ptr<metrics_api::MeterProvider> none;
    metrics_api::Provider::SetMeterProvider(none);
}

void TestCallback(opentelemetry::metrics::ObserverResult observer_result,
                  void * /* state */) {
    if (nostd::holds_alternative<nostd::shared_ptr<
            opentelemetry::metrics::ObserverResultT<int64_t>>>(
            observer_result)) {
        nostd::get<nostd::shared_ptr<
            opentelemetry::metrics::ObserverResultT<int64_t>>>(observer_result)
            ->Observe(value++);
    }
}

int main(int argc, char **argv) {
    std::string name{"ostream_metric_example"};
    InitMetrics(name);

    auto provider = metrics_api::Provider::GetMeterProvider();
    nostd::shared_ptr<metrics_api::Meter> meter =
        provider->GetMeter(name, "1.2.0");

    auto test_counter =
        meter->CreateInt64ObservableUpDownCounter("test_counter");
    test_counter->AddCallback(TestCallback, nullptr);

    while (true);

    CleanupMetrics();
}
```

**What is the expected behavior?**
The values are reported as 3, 4, 5, 6, etc.
```
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:30 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 3
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:35 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 4
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:40 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 5
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
```

**What is the actual behavior?**
The values are reported as 3, **7**, 8, 9, etc.
<pre><code>
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:30 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 3
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:35 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 7
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
{
  scope name    : ostream_metric_example
  schema url    :
  version       : 1.2.0
  start time    : Tue Sep  5 14:50:30 2023
  end time      : Tue Sep  5 14:50:40 2023
  instrument name       : test_counter
  description   :
  unit          :
  type          : SumPointData
  value         : 8
  attributes            :
  resources     :
        service.name: unknown_service
        telemetry.sdk.language: cpp
        telemetry.sdk.name: opentelemetry
        telemetry.sdk.version: 1.9.0
}
</code></pre>

**Additional Info**
I tried to reproduce the same issue with:
- the Opentelemetry-Python SDK, but that reported the correct values (3, 4, 5, 6 etc.)
- Opentelemetry-cpp v1.11.0 and was able to successfully do so.

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #2296

## Changes
The default aggregation type was not handled properly for Observable Counter/UpDownCounter, and the issue was surfaced/evident out with non-zero initial measurement value. Have fixed the issue. Also we were missing the test for Observable UpDownCounter. Have added the test to catch this error.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h [hunk 1]
```diff
@@ -159,7 +160,29 @@ class DefaultAggregation
               new DoubleSumAggregation(nostd::get<SumPointData>(point_data)));
         }
       default:
-        return DefaultAggregation::CreateAggregation(instrument_descriptor, nullptr);
+        return nullptr;  // won't reach here
```
Comment (ThomsonTan) [inline sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:163]: Add an assert here?

File: sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h [hunk 2]
```diff
@@ -159,7 +160,29 @@ class DefaultAggregation
...
+        return AggregationType::kSum;
+      case InstrumentType::kHistogram:
+        return AggregationType::kHistogram;
+      case InstrumentType::kObservableGauge:
+        return AggregationType::kLastValue;
+      default:
+        return AggregationType::kDrop;
     }
   }
 };
```
Comment (marcalff) [inline sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:188]: I don't understand the semantic here, what does `is_monotonic` means ?

Counter and Observable counter are not monotonic but everything else is ?

This looks like inverted logic (compared to my understanding of a counter).

Please clarify.

**Review by marcalff — COMMENTED** [review]
Starting review, just a question for now.

File: sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h (hunk 2 above)
Comment (lalitb) [reply sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:188]: Your understanding is correct :) The logic is incorrectly inverted in this PR. And since we don't have negative values in UpDownCounter unit-test, there was no error. I have now changed the unit-test to record negative values, and let the test fail first before fixing.

Comment (lalitb) [reply sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:188]: Ok, I can see the test failing now:
```
The following tests FAILED:
Errors while running CTest
	313 - metrics.*/WritableMetricStorageTestUpDownFixture.TestAggregation/* (Failed)
```

Adding fix now.

Comment (lalitb) [reply sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:188]: Added fix. The unit-test is passing now.
Thanks for noticing the issue.

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the fix.

File: sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h (hunk 1 above)
Comment (lalitb) [reply sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h:163]: Thanks, will look into this separately. Not a big fan of adding assert in telemetry sdk. But returning `nullptr` (even for unreachable code) is also not nice thing. Probaby we can return DropAggregation just to be cautious. Will create a issue to track this.
