### PR TITLE
[CI] build iwyu

### LINKED ISSUE #3453: Segmentation fault in iwyu ci job
The IWYU CI job logs a segmentation fault and succeeds. 

https://github.com/open-telemetry/opentelemetry-cpp/actions/runs/15320806098/job/43103944715#step:8:1644

```bash
Error running 'include-what-you-use': Segmentation fault
make[2]: *** [exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/build.make:79: exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/src/otlp_grpc_client.cc.o] Error 1
[ 71%] Building CXX object exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/src/otlp_grpc_client_factory.cc.o
[ 71%] Building CXX object exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/src/otlp_grpc_utils.cc.o
make[2]: Target 'exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:8306: exporters/otlp/CMakeFiles/opentelemetry_exporter_otlp_grpc_client.dir/all] Error 2
```
The iwyu tool never finishes the build and stops due to the error. 
```
[ 95%] Built target func_otlp_http
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:166: all] Error 2
make: Target 'default_target' not remade because of errors.
```

We are installing iwyu with apt and using version 8.21. A newer version may be available.

```bash
Get:13 http://azure.archive.ubuntu.com/ubuntu noble/universe amd64 iwyu amd64 8.21-1build2 [681 kB]
```

### PR DESCRIPTION
**Pull request by dbarker**
Fixes #3453
 
Build iwyu to upgrade to version 0.22 and fix the segfault.

## Changes

- adds an iwyu install script and uses it in the ci workflow and devcontainer
- install grpc with apt on the iwyu ci runner
- remove installing iwyu apt package elsewhere

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by marcalff** [comment]
Looks good.

Suggested changes:

1)

In `iwyu.yml`, in the count warning section, print the iwyu version.

2)

In the same place, raise `WARNING_LIMIT` to 122, to make CI pass with warnings.

It seem recent versions of iwyu report different diagnostics, causing new warnings.

Assuming that the new diagnostics with a recent iwyu version are more accurate and corresponds to bugs fixed in the tool, we have no choice but comply with the updated diagnostics then.

Warnings to be cleaned in a separate PR, to get down to 0 again.

File: ci/install_iwyu.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+echo "LLVM_VERSION=$LLVM_VERSION"
+echo "Installing IWYU..."
+
+cd /tmp
+git clone --depth 1 --branch clang_$LLVM_VERSION https://github.com/include-what-you-use/include-what-you-use.git
+cd include-what-you-use
+mkdir -p build
+cd build
+
+cmake -DCMAKE_PREFIX_PATH=/usr/lib/llvm-$LLVM_VERSION -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
```
Comment (ThomsonTan) [inline ci/install_iwyu.sh:26]: Set CMAKE_BUILD_TYPE to Release?

Comment (dbarker) [reply ci/install_iwyu.sh:26]: The instructions for building iwyu don't set any optimizations so I'd lean towards leaving it as is. The segfault is gone :)
