### PR TITLE
[CODE HEALTH] Fix clang-tidy misc-use-internal-linkage warnings

### LINKED ISSUE #3977: [CODE HEALTH] clang-tidy misc-use-internal-linkage warnings
clang-tidy reports the following warnings: 

----

**misc-use-internal-linkage** (4 warnings)

| File | Line | Message |
|---|---|---|
| `opentelemetry-cpp/examples/common/foo_library/foo_library.cc` | 36 | function 'foo_library' can be made static or moved into an anonymous namespace to enforce internal linkage |
| `opentelemetry-cpp/examples/common/logs_foo_library/foo_library.cc` | 34 | function 'foo_library' can be made static or moved into an anonymous namespace to enforce internal linkage |
| `opentelemetry-cpp/functional/otlp/func_grpc_main.cc` | 356 | function 'list_test_cases' can be made static or moved into an anonymous namespace to enforce internal linkage |
| `opentelemetry-cpp/sdk/test/common/circular_buffer_benchmark.cc` | 58 | variable 'random_number_generator' can be made static or moved into an anonymous namespace to enforce internal linkage |

----

To reproduce locally run the following in the development container: 
```
export CXX_STANDARD=14
./ci/do_ci.sh cmake.clang_tidy.test
```

The markdown report with unique errors can be generated locally after building with the `ci/create_clang_tidy_report.py` script.

### PR DESCRIPTION
**Pull request by mateenali66**
Fixes #3977

marked `list_test_cases` in `func_grpc_main.cc` as static since it is only called in the same TU, and added `static` to the `thread_local` RNG in `circular_buffer_benchmark.cc`. the two `foo_library` functions in `examples/common/foo_library` and `examples/common/logs_foo_library` are exported via headers and linked into many example binaries, so internal linkage is not possible there. suppressed those with NOLINTNEXTLINE.

also decremented the clang-tidy warning limits by 4 to match the reduced unique warning count, consistent with prior code-health PRs.

keeping as draft until clang-tidy CI confirms the new limits are correct.

## Changes

* Fix clang-tidy `misc-use-internal-linkage` warnings.

For significant contributions please make sure you have completed the following items:

* [X] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: examples/common/foo_library/foo_library.cc [hunk 1]
```diff
@@ -33,6 +33,7 @@ void f2()
 }
 }  // namespace
 
+// NOLINTNEXTLINE(misc-use-internal-linkage)
```
Comment (dbarker) [inline examples/common/foo_library/foo_library.cc]: The header "foo_library/foo_library.h" is not included in the foo_library.cc. Including it should fix the warning.

File: examples/common/logs_foo_library/foo_library.cc [hunk 2]
```diff
@@ -31,6 +31,7 @@ opentelemetry::nostd::shared_ptr<logs::Logger> get_logger()
 }
 }  // namespace
 
+// NOLINTNEXTLINE(misc-use-internal-linkage)
```
Comment (dbarker) [inline examples/common/logs_foo_library/foo_library.cc]: Same as above. Can this be fixed with including "logs_foo_library/foo_library.h"?

**Review by dbarker — COMMENTED** [review]
Thanks for the cleanup! A few minor comments about the missing header includes which should fix the foo_library warnings.

File: examples/common/foo_library/foo_library.cc (hunk 1 above)
Comment (mateenali66) [reply examples/common/foo_library/foo_library.cc]: addressed in the latest commit. included foo_library/foo_library.h directly, removed the NOLINT. used the same BAZEL_BUILD vs CMake include guard pattern as the example main files.

File: examples/common/logs_foo_library/foo_library.cc (hunk 2 above)
Comment (mateenali66) [reply examples/common/logs_foo_library/foo_library.cc]: same fix, included logs_foo_library/foo_library.h in the logs variant and dropped the NOLINT there too.

**Review by dbarker — APPROVED** [review]
Looks good. Thanks for the contribution!

**Review by marcalff — APPROVED** [review]
LGTM, thanks for the cleanup.
