### PR TITLE
Fix: 1712 -  Validate Instrument meta data (name, unit, description)

### LINKED ISSUE #1712: [Metrics SDK] - Validate Instrument meta data (name, unit, description)
Metrics Specs specifies the Instrument naming rules - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-naming-rule

Valid Instruments should be created only if the `name`, `unit` and `description` are compliant with these naming rules.

Also, adding it after GA would be a breaking change specifically for the non-compliant instruments created before enabling this validation. Once validation is enabled, it won't be possible to send the metrics for these non-compliant instruments.
So scoping this for GA.

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #1712

## Changes

- Create valid instrument if the meta data is validated
- Else, create noop-instrument.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [x] Unit tests have been added
* [x] Changes in public API reviewed

### CODE REVIEW

File: sdk/src/metrics/meter.cc [hunk 1]
```diff
@@ -39,6 +40,13 @@ nostd::unique_ptr<metrics::Counter<uint64_t>> Meter::CreateUInt64Counter(
     nostd::string_view description,
     nostd::string_view unit) noexcept
 {
+  if (!ValidateInstrument(name, description, unit))
+  {
+    OTEL_INTERNAL_LOG_ERROR("Meter::CreateUInt64Counter - failed. Invalid parameters."
+                            << name << " " << description << " " << unit);
+    return nostd::unique_ptr<metrics::Counter<uint64_t>>(
+        new metrics::NoopCounter<uint64_t>(name, description, unit));
```
Comment (marcalff) [inline sdk/src/metrics/meter.cc:48]: The calling instrumented application will not notice the error if returning a noop counter.

Not crashing now with a noop is not helping.
Instead, bugs will be filed later against opentelemetry-cpp about instrument that produce no data.

How about returning a nullptr, forcing the calling application to do something about it ?

Comment (lalitb) [reply sdk/src/metrics/meter.cc:48]: Yes, good point. I too thought about it, but also felt that making some critical application crash for some issue in telemetry configuration is not a good idea.  We can also be more explicit in error message stating that measurements won't be recorded.

This is also inline with the general error handling [guidelines ](https://github.com/jack-berg/opentelemetry-specification/blob/6307e44b88dd8f654134946c765cd22dc01c8455/specification/error-handling.md#error-handling-and-performance) - 
``
Whenever API call returns values that is expected to be non-null value - in case of error in processing logic - SDK MUST return a "no-op" or any other "default" object that was (ideally) pre-allocated and readily available. This way API call sites will not crash on attempts to access methods and properties of a null objects.
``

File: api/include/opentelemetry/common/macros.h [hunk 2]
```diff
@@ -90,6 +90,14 @@
 #  define OPENTELEMETRY_DEPRECATED_MESSAGE(msg)
 #endif
 
+// Regex support
+#if (__GNUC__ == 4 && (__GNUC_MINOR__ == 8 || __GNUC_MINOR__ == 9))
```
Comment (ThomsonTan) [inline api/include/opentelemetry/common/macros.h:94]: nit: __GNUC_MINOR__ >= 8?

File: sdk/src/metrics/instrument_metadata_validator.cc [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+const std::string kInstrumentNamePattern = "[a-zA-Z][-_.a-zA-Z0-9]{0,62}";
+//
+const std::string kInstrumentUnitPattern = "[\x01-\x7F]{0,63}";
+// instrument-unit = It can have a maximum length of 63 ASCII chars
+
+InstrumentMetaDataValidator::InstrumentMetaDataValidator()
+#  if HAVE_WORKING_REGEX
+    : name_reg_key_{kInstrumentNamePattern}, unit_reg_key_
+{
+  kInstrumentUnitPattern
```
Comment (ThomsonTan) [inline sdk/src/metrics/instrument_metadata_validator.cc:28]: Was this line formatted by clang-format? The format looks a little weird.

File: sdk/src/metrics/instrument_metadata_validator.cc [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+}
+#  endif
+{}
```
Comment (ThomsonTan) [inline sdk/src/metrics/instrument_metadata_validator.cc:31]: Should this be put under `#else` block?

File: api/include/opentelemetry/common/macros.h (hunk 2 above)
Comment (lalitb) [reply api/include/opentelemetry/common/macros.h:94]: The regex support is partially implemented for gcc 4.8 and gcc 4.9 only. So the existing condition looks good to me.

File: sdk/src/metrics/instrument_metadata_validator.cc (hunk 3 above)
Comment (lalitb) [reply sdk/src/metrics/instrument_metadata_validator.cc]: yeah clang-format behaved weirdly here. I have disable the clang-format for this block of code. Looks better now.
Thanks for noticing.

File: sdk/src/metrics/instrument_metadata_validator.cc (hunk 4 above)
Comment (lalitb) [reply sdk/src/metrics/instrument_metadata_validator.cc:31]: no it's fine actually. The part of code was somewhat confusing with clang-format. It should be more clear now.

File: sdk/src/metrics/instrument_metadata_validator.cc [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+{
+#  if HAVE_WORKING_REGEX
+  return std::regex_match(name.data(), name_reg_key_);
+#  else
+  // size atmost 63 chars
+  if (name.size() > kMaxSize)
+  {
+    return false;
+  }
+  // first char should be alphanumeric
```
Comment (ThomsonTan) [inline sdk/src/metrics/instrument_metadata_validator.cc:43]: First char should be alpha, not alphanumeric?

File: api/include/opentelemetry/common/macros.h (hunk 2 above)
Comment (lalitb) [reply api/include/opentelemetry/common/macros.h:94]: But yeah, even  GNUC_MINOR >= 8 should work fine. But let it be explicit I think :)

File: sdk/src/metrics/instrument_metadata_validator.cc (hunk 5 above)
Comment (lalitb) [reply sdk/src/metrics/instrument_metadata_validator.cc]: yeah good point. fixed the comment.

File: sdk/src/metrics/meter.cc (hunk 1 above)
Comment (marcalff) [reply sdk/src/metrics/meter.cc:49]: Thanks for the details. Ok with noop then.

File: sdk/src/metrics/meter.cc [hunk 6]
```diff
@@ -52,6 +61,14 @@ nostd::unique_ptr<metrics::Counter<double>> Meter::CreateDoubleCounter(
     nostd::string_view description,
     nostd::string_view unit) noexcept
 {
+  if (!ValidateInstrument(name, description, unit))
+  {
+    OTEL_INTERNAL_LOG_ERROR("Meter::CreateDoubleCounter - failed. Invalid parameters."
```
Comment (ThomsonTan) [inline sdk/src/metrics/meter.cc:66]: nit: probably use macro `__func__` to avoid hard code function name in string liternal.

File: sdk/test/metrics/instrument_metadata_validator_test.cc [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+      "d1234_-sDSDs.sdsd344",                 // combination of all valid characters
+      CreateVeryLargeString(5) + "ABCERTYG",  // total 63 charactes
+  };
+  for (auto const &str : valid_names)
+  {
+    EXPECT_TRUE(validator.ValidateName(str));
+  }
+}
+
+TEST(InstrumentMetadataValidator, TestUnit)
```
Comment (ThomsonTan) [inline sdk/test/metrics/instrument_metadata_validator_test.cc:49]: Missing unit test on description?

**Review by ThomsonTan — APPROVED** [review]

File: sdk/test/metrics/instrument_metadata_validator_test.cc (hunk 7 above)
Comment (lalitb) [reply sdk/test/metrics/instrument_metadata_validator_test.cc:49]: We don't have any validation checks for the description, so no tests added for it.

File: sdk/src/metrics/meter.cc (hunk 6 above)
Comment (lalitb) [reply sdk/src/metrics/meter.cc:66]: yes, probably we can modify `OTEL_INTERNAL_*` macros to automatically add class and method name to the logs.
