### PR TITLE
Fix 2110

### LINKED ISSUE #2110: Http sessions will not be clean if it's abort without curl event notification.
**Describe your environment** 

OS: Linux
Compiler: GCC 12.2.0
curl version: 8.0.1

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**

When shutdown, all sessions shoud be cleanup and exit.

**What is the actual behavior?**

If libcurl miss the notification when shutdown, http client will wait for running sessions for ever,because it will not be notified and will not be consumed.

**Additional context**

It's base our use case and I didn't find a easy way to reproduce easily.

### PR DESCRIPTION
**Pull request by owent**
Fixes #2110 

## Changes

Please provide a brief description of the changes here.

+ Record aborted session and call it's `FinishOperation`.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

File: ext/src/http/client/curl/http_client_curl.cc [hunk 1]
```diff
@@ -258,7 +258,7 @@ void HttpClient::CleanupSession(uint64_t session_id)
       else if (session->IsSessionActive() && session->GetOperation())
       {
         // If this session is alread waiting to be removed, just wakeup background thread to call
-        // doRemoveSessions()
+        pending_to_abort_sessions_[session_id] = std::move(session);
```
Comment (marcalff) [inline ext/src/http/client/curl/http_client_curl.cc:261]: The comment had 2 lines, one of them removed, so now it reads:

// If this session is alread waiting to be removed, just wakeup background thread to call

Please reword it, and fix typo (alread -> already) while at it.

If I understood correctly:

// If this session is already waiting to be removed, give it to the background thread for cleanup.

**Review by marcalff — APPROVED** [review]
LGTM, only minor comments.

File: ext/src/http/client/curl/http_client_curl.cc (hunk 1 above)
Comment (owent) [reply ext/src/http/client/curl/http_client_curl.cc:261]: Thanks.

**Review by lalitb — APPROVED** [review]

**Review by ThomsonTan — APPROVED** [review]
